// Generated by scripts/gen_frontend.py. Edit that, not this file.

import pluginVue from 'eslint-plugin-vue'

// The guard. Every native control here has a frappe-ui equivalent, and using the
// raw element is how a design system quietly stops being one — a plain <button>
// looks close enough in isolation and wrong next to everything else.
//
// Escape hatch is a one-line eslint-disable with a reason, so bypassing it is a
// visible decision rather than an accident.
const BANNED = [
  { element: 'button', message: 'Use <Button> from @/ui instead of a raw <button>.' },
  { element: 'input', message: 'Use <TextInput>, <FormControl>, <Checkbox> or <Switch> from @/ui.' },
  { element: 'select', message: 'Use <Select> or <Autocomplete> from @/ui.' },
  { element: 'textarea', message: 'Use <Textarea> or <FormControl type="textarea"> from @/ui.' },
  { element: 'dialog', message: 'Use <Dialog> from @/ui.' },
  { element: 'table', message: 'Use <ListView> from frappe-ui/list.' },
]

export default [
  ...pluginVue.configs['flat/recommended'],
  {
    files: ['src/**/*.vue'],
    rules: {
      'vue/no-restricted-html-elements': ['error', ...BANNED],
      'vue/multi-word-component-names': 'off',
      'vue/no-v-html': 'error',

      // Formatting is a formatter's job. Left on, these produce dozens of
      // warnings per file and train everyone to ignore lint output — which is
      // where the rules that actually matter live.
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-self-closing': 'off',
      'vue/html-indent': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/attributes-order': 'off',
      'vue/first-attribute-linebreak': 'off',
    },
  },
  {
    // The shared runtime is exempt — it is what wraps frappe-ui.
    files: ['src/**/*.{js,vue}'],
    ignores: ['src/ui.js', 'src/lib/**'],
    rules: {
      'no-restricted-imports': ['error', {
        paths: [
          {
            name: 'frappe-ui',
            // Two separate reasons, both load-bearing:
            //  - components: '@/ui' is the one reviewable list of what is allowed
            //  - data/notify: '@/lib/resource' and '@/lib/notify' are what apply
            //    response unwrapping, Frappe error parsing, toasts and sound
            message:
              "Import components from '@/ui', data helpers from '@/lib/resource', " +
              "and toasts from '@/lib/notify'. Going direct skips error parsing, " +
              'response unwrapping and notification sound.',
          },
          {
            name: 'frappe-ui/list',
            message: "Import list components from '@/ui' too — one import path " +
              'for the whole sanctioned surface.',
          },
          {
            name: 'frappe-ui/editor',
            message: "Import the editor from '@/ui' too — one import path for " +
              'the whole sanctioned surface.',
          },
          {
            // The unstable entry point, so the one reviewable list matters
            // more here rather than less: a breaking change upstream should
            // show up in one file, not in however many reached for it.
            name: 'frappe-ui/experimental',
            message: "Import experimental components from '@/ui' too. They " +
              'carry no backward-compatibility promise, so the barrel is what ' +
              'keeps the blast radius to one file.',
          },
          {
            name: 'frappe-ui/charts',
            message: "Import charts from '@/ui' too. They pull echarts in, so " +
              'the one reviewable list is also the one place that decides ' +
              'what a page pays for.',
          },
          {
            name: 'socket.io-client',
            message: "Use onDoctypeChange from '@/lib/socket' — one shared, " +
              'reference-counted socket per app.',
          },
        ],
      }],
      // console.error is deliberate in the error normaliser; noise elsewhere.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    // The layout primitives belong to AppShell and nothing else.
    //
    // DesktopShell and MobileShell are different components with different
    // slots, so every surface that composes them directly makes its own choice
    // about the breakpoint, about whether a rail appears, and about how a phone
    // reaches the app switcher. Two surfaces choosing differently is how one
    // account starts looking like two products on the same tablet — and the
    // mobile shell has no rail slot at all, so 'just use MobileShell' silently
    // drops app switching.
    files: ['src/**/*.vue'],
    ignores: ['src/components/AppShell.vue'],
    rules: {
      'no-restricted-imports': ['error', {
        paths: [{
          name: '@/ui',
          importNames: [
            'DesktopShell', 'MobileShell', 'MobileNav', 'MobileNavItem',
            'Rail', 'RailItem',
          ],
          message:
            'Compose <AppShell> instead. It owns the desktop/mobile split, the ' +
            'rail, and the bottom-bar app switcher, so every surface agrees.',
        }],
      }],
    },
  },
]
