// Generated by scripts/gen_frontend.py. Edit that, not this file.

import pluginVue from 'eslint-plugin-vue'

// The guard. Every native control here has a frappe-ui equivalent, and using the
// raw element is how a design system quietly stops being one — a plain <button>
// looks close enough in isolation and wrong next to everything else.
//
// Escape hatch is a one-line eslint-disable with a reason, so bypassing it is a
// visible decision rather than an accident.
const BANNED = [
  { element: 'button', message: 'Use <Button> from @/ui instead of a raw <button>.' },
  { element: 'input', message: 'Use <TextInput>, <FormControl>, <Checkbox> or <Switch> from @/ui.' },
  { element: 'select', message: 'Use <Select> or <Autocomplete> from @/ui.' },
  { element: 'textarea', message: 'Use <Textarea> or <FormControl type="textarea"> from @/ui.' },
  { element: 'dialog', message: 'Use <Dialog> from @/ui.' },
  { element: 'table', message: 'Use <ListView> from frappe-ui/list.' },
]

export default [
  ...pluginVue.configs['flat/recommended'],
  {
    files: ['src/**/*.vue'],
    rules: {
      'vue/no-restricted-html-elements': ['error', ...BANNED],
      'vue/multi-word-component-names': 'off',
      'vue/no-v-html': 'error',
    },
  },
  {
    // The shared runtime is exempt — it is what wraps frappe-ui.
    files: ['src/**/*.{js,vue}'],
    ignores: ['src/ui.js', 'src/lib/**'],
    rules: {
      'no-restricted-imports': ['error', {
        paths: [
          {
            name: 'frappe-ui',
            // Two separate reasons, both load-bearing:
            //  - components: '@/ui' is the one reviewable list of what is allowed
            //  - data/notify: '@/lib/resource' and '@/lib/notify' are what apply
            //    response unwrapping, Frappe error parsing, toasts and sound
            message:
              "Import components from '@/ui', data helpers from '@/lib/resource', " +
              "and toasts from '@/lib/notify'. Going direct skips error parsing, " +
              'response unwrapping and notification sound.',
          },
          {
            name: 'socket.io-client',
            message: "Use onDoctypeChange from '@/lib/socket' — one shared, " +
              'reference-counted socket per app.',
          },
        ],
      }],
      // console.error is deliberate in the error normaliser; noise elsewhere.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
]
