// Generated by scripts/gen_frontend.py. Edit that, not this file.

// Visual checks against a real local site, not a mocked one.
//
// The bugs this exists to catch — an empty list, a dialog that will not open, a
// control unreachable at one viewport — all render without throwing, so unit
// tests and a clean build say nothing about them. Only looking does.
//
// Start the site this points at first:
//   ONEAPP_SITE=control.localhost ONEAPP_PORT=8000 scripts/dev.sh up
import { defineConfig, devices } from '@playwright/test'

// The image ships one Chromium build and this runner expects another;
// `playwright install` is disabled here, so point at what exists rather than
// letting it try to download a build it will never get.
const CHROMIUM =
  process.env.ONEAPP_CHROMIUM || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome'
const launchOptions = { executablePath: CHROMIUM }

export default defineConfig({
  testDir: './e2e',
  // One worker, for two reasons that are easy to mistake for one.
  //
  // The first is correctness. Every spec drives the *same* seeded space and
  // several write the same record — a comment count, an assignment, a rename,
  // a heart. At four workers six specs fail on data another worker moved:
  // child-table, follow, import, realtime, record-surface and space. That is a
  // suite that is faster and no longer tells the truth.
  //
  // The second is that the speed is not there anyway. This machine has four
  // cores and the site is one GIL-bound Python process, so the browsers and
  // the server contend for the same four. Measured rather than assumed: the
  // desktop project is 3.5 minutes at four workers against about 4.75 at one,
  // and concurrent API calls plateau at 1.9x by two-way concurrency.
  //
  // So the honest fix is a seeded space per worker keyed on `parallelIndex`,
  // and even that returns under 2x here. It is not a config change and it is
  // not the biggest win available — that one is not running all 260 of these
  // for a change that touched three files.
  //
  // While iterating, run the specs you are changing:
  //   npx playwright test theme.spec.js --project=desktop
  // `yarn e2e:fast` is the same idea with the parallelism turned up, for a
  // handful of read-only specs. `yarn e2e` before a commit.
  workers: Number(process.env.ONEAPP_E2E_WORKERS || 1),
  reporter: [['list']],
  // Retried once, and only the retry is traced. `retain-on-failure` records
  // every test and throws away all but the failures, which is a tax on the
  // ninety-nine that pass to keep the one that does not.
  retries: 1,
  timeout: 45_000,
  use: {
    // The site by its own hostname, not `localhost`. Frappe's socketio server
    // works out which site a socket belongs to from the Origin header and
    // refuses a namespace that does not match it — so on `localhost` every
    // connection came back "Invalid namespace" and realtime was silently off
    // for the whole browser pass. `*.localhost` resolves without a hosts file
    // entry, and this is also how the site is addressed in production.
    baseURL: process.env.ONEAPP_BASE_URL || 'http://control.localhost:8000',
    screenshot: 'only-on-failure',
    trace: 'on-first-retry',
  },
  projects: [
    { name: 'desktop', use: { ...devices['Desktop Chrome'], launchOptions } },
    // The screenshot that started this was a phone: no sidebar, so anything
    // that lives only there is unreachable.
    { name: 'mobile', use: { ...devices['Pixel 7'], launchOptions } },
  ],
})
