// Generated by scripts/gen_frontend.py. Edit that, not this file.

// Visual checks against a real local site, not a mocked one.
//
// The bugs this exists to catch — an empty list, a dialog that will not open, a
// control unreachable at one viewport — all render without throwing, so unit
// tests and a clean build say nothing about them. Only looking does.
//
// Start the site this points at first:
//   ONEAPP_SITE=control.localhost ONEAPP_PORT=8000 scripts/dev.sh up
import { defineConfig, devices } from '@playwright/test'

// The image ships one Chromium build and this runner expects another;
// `playwright install` is disabled here, so point at what exists rather than
// letting it try to download a build it will never get.
const CHROMIUM =
  process.env.ONEAPP_CHROMIUM || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome'
const launchOptions = { executablePath: CHROMIUM }

export default defineConfig({
  testDir: './e2e',
  // One worker: these drive a single shared site, and parallel logins race on
  // the same session.
  // One worker, and it is the fixture rather than the browser that decides.
  // Every spec drives one seeded space on one site, and several of them write
  // to the same record — a comment count, an assignment, a rename. Four
  // workers finish in a little over half the time and two specs fail on data
  // another worker changed underneath them, which is a suite that is faster
  // and no longer tells the truth.
  //
  // Making it safely parallel means a seeded space per worker, keyed on
  // `parallelIndex`. That is worth doing and it is not a config change.
  //
  // Meanwhile: `yarn e2e:fast` is the loop to develop against — one project,
  // four workers, for the specs you are working on. Run `yarn e2e` before a
  // commit.
  workers: Number(process.env.ONEAPP_E2E_WORKERS || 1),
  reporter: [['list']],
  // Retried once, and only the retry is traced. `retain-on-failure` records
  // every test and throws away all but the failures, which is a tax on the
  // ninety-nine that pass to keep the one that does not.
  retries: 1,
  timeout: 45_000,
  use: {
    // The site by its own hostname, not `localhost`. Frappe's socketio server
    // works out which site a socket belongs to from the Origin header and
    // refuses a namespace that does not match it — so on `localhost` every
    // connection came back "Invalid namespace" and realtime was silently off
    // for the whole browser pass. `*.localhost` resolves without a hosts file
    // entry, and this is also how the site is addressed in production.
    baseURL: process.env.ONEAPP_BASE_URL || 'http://control.localhost:8000',
    screenshot: 'only-on-failure',
    trace: 'on-first-retry',
  },
  projects: [
    { name: 'desktop', use: { ...devices['Desktop Chrome'], launchOptions } },
    // The screenshot that started this was a phone: no sidebar, so anything
    // that lives only there is unreachable.
    { name: 'mobile', use: { ...devices['Pixel 7'], launchOptions } },
  ],
})
