// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * One screen, as a PNG. `yarn shot <path> [file.png]`.
 *
 * Looking at a change is the shortest question you can ask this product, and it
 * used to be one of the most expensive: sign in, drive the app to the screen,
 * wait for the rows, screenshot — twenty lines written from scratch every time
 * somebody wanted to see something, and got slightly wrong every time. The
 * login form rather than the endpoint. A fixed sleep rather than a wait. A
 * browser Playwright then tried to download.
 *
 *   yarn shot '/one/space/rua?screen=projects'
 *   yarn shot '/one/space/rua?screen=projects' rua.png --phone
 *   yarn shot '/one/space/rua?screen=projects' --wait='[data-slot="list-row"]'
 *
 * `--wait` is the flag worth knowing: a selector to wait for before the
 * shutter. Without one this waits for the network to go quiet, which is right
 * for most screens and wrong for any that keeps a socket open. Give it the
 * thing you are actually looking at.
 *
 * The rest: `--phone` for the suite's phone viewport, `--full` for the whole
 * scrollable page, `--retina` when the detail is the point, `--settle=MS` for
 * an animation this does not know about.
 *
 * `--tokens=--a,--b` prints those CSS custom properties as the page resolves
 * them, which is the only way to check a *declared* look actually arrived: a
 * one-pixel tab indicator is a token you can read and a colour you cannot see
 * in a screenshot, and the difference between "the theme is wrong" and "the
 * line is thin" is otherwise an afternoon.
 *
 * Nothing here builds. `scripts/dev.sh watch` keeps the bundle current, so the
 * loop is edit, look — not edit, build, look.
 */
import { chromium } from '@playwright/test'
import { signIn } from './e2e/auth.js'
// The site, and the browser to open it with, read from the suite's own config
// rather than restated here. Both are things this environment gets wrong in a
// way that wastes an afternoon — the image ships one Chromium build and the
// runner expects another — and having the answer in two places is how one of
// them goes stale without anybody noticing.
import config from './playwright.config.js'

const args = process.argv.slice(2)
const flag = (name, fallback) => {
  const found = args.find((one) => one.startsWith(`--${name}=`))
  return found === undefined ? fallback : found.slice(name.length + 3)
}
const has = (name) => args.includes(`--${name}`)
const positional = args.filter((one) => !one.startsWith('--'))

const path = positional[0]
if (!path) {
  console.error(
    'usage: yarn shot <path> [out.png] ' +
      '[--wait=SELECTOR] [--phone] [--full] [--retina] [--settle=MS] ' +
      '[--tokens=--a,--b]',
  )
  process.exit(1)
}
const out = positional[1] || 'shot.png'
const base = process.env.ONEAPP_BASE_URL || config.use.baseURL

// The project whose viewport this is, so what you look at is what the tests
// look at rather than a size chosen here.
const named = has('phone') ? 'mobile' : 'desktop'
const project = config.projects.find((one) => one.name === named) || config.projects[0]
const viewport = flag('width')
  ? { width: Number(flag('width')), height: Number(flag('height', 900)) }
  : project.use.viewport

const browser = await chromium.launch(project.use.launchOptions)
const context = await browser.newContext({
  viewport,
  // 1x by default: these get looked at and sent around, and a retina PNG is
  // four times the bytes for something somebody will glance at.
  deviceScaleFactor: has('retina') ? 2 : 1,
})
const page = await context.newPage()

// Said out loud afterwards, because a screenshot of a broken screen is not
// obviously a screenshot of a broken screen — it is usually just empty.
const complaints = []
page.on('pageerror', (e) => complaints.push(String(e)))
page.on('response', (r) => {
  if (r.status() >= 400) complaints.push(`${r.status()} ${r.url()}`)
})

try {
  await signIn(page, base)
  await page.goto(base + path)
  const wait = flag('wait')
  if (wait) await page.locator(wait).first().waitFor({ timeout: 40_000 })
  else await page.waitForLoadState('networkidle').catch(() => {})
  // A beat for the last transition to land. Short, because `--wait` is the
  // right answer whenever it actually matters.
  await page.waitForTimeout(Number(flag('settle', 600)))
  await page.screenshot({ path: out, fullPage: has('full') })
  console.log(out)

  const asked = flag('tokens')
  if (asked) {
    const values = await page.evaluate((names) => {
      const style = getComputedStyle(document.documentElement)
      return names.map((one) => [one, style.getPropertyValue(one).trim()])
    }, asked.split(',').map((one) => one.trim()).filter(Boolean))
    for (const [name, value] of values) console.log(`${name}: ${value || '(unset)'}`)
  }
  if (complaints.length) {
    console.log('---')
    for (const one of [...new Set(complaints)].slice(0, 10)) console.log(one)
  }
} finally {
  await browser.close()
}
