// Generated by scripts/gen_frontend.py. Edit that, not this file.

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import frappeui from 'frappe-ui/vite'
import fs from 'node:fs'
import path from 'node:path'

// Frappe serves one .html per website route. frappe-ui's plugin emits exactly
// one, so the additional surfaces are copies of it — same hashed asset tags,
// different <title>, and a sibling .py that decides who may load them. Copying
// after the build is what guarantees they can never reference stale assets.
const EXTRA_SHELLS = [{"name": "portal", "title": "OneSpace"}]

function extraShells() {
  return {
    name: 'oneapp-extra-shells',
    closeBundle() {
      if (!EXTRA_SHELLS.length) return
      const source = path.resolve(__dirname, '../oneapp_control/www/admin.html')
      if (!fs.existsSync(source)) {
        // Silently skipping would ship a route that 404s with nothing to
        // explain why, so fail the build instead.
        throw new Error(`extraShells: ${source} was not emitted by frappe-ui`)
      }
      const html = fs.readFileSync(source, 'utf8')
      for (const shell of EXTRA_SHELLS) {
        fs.writeFileSync(
          path.resolve(__dirname, `../oneapp_control/www/${shell.name}.html`),
          html.replace(/<title>[^<]*<\/title>/, `<title>${shell.title}</title>`),
        )
      }
    },
  }
}

// frappe-ui's plugin owns the parts that are easy to get subtly wrong: it
// proxies /api, /app, /assets, /files and /private to the bench it detects from
// common_site_config.json, and it emits ../oneapp_control/www/<route>.html so the SPA is
// served by Frappe itself. Hand-rolling any of that is how the two apps drift.
export default defineConfig({
  plugins: [
    frappeui({
      frontendRoute: '/admin',
      // Given explicitly rather than inferred. frappe-ui derives these by
      // walking up for a bench layout (a directory with both sites/ and apps/),
      // which exists on Frappe Cloud but not in this monorepo — so inference
      // returns null here and the production build fails with
      // "indexHtmlPath is required". Stating them makes the build identical
      // everywhere: monorepo, bench, and CI.
      buildConfig: {
        outDir: path.resolve(__dirname, '../oneapp_control/public/frontend'),
        indexHtmlPath: '../oneapp_control/www/admin.html',
      },
      frappeTypes: {
        input: {
  'oneapp_control': [
    'Tenant',
    'Shard',
    'Plan',
    'Subscription',
    'Provisioning Job',
    'Credit Ledger Entry',
    'OneSpace Space'
  ]
},
      },
    }),
    vue(),
    extraShells(),
  ],
  resolve: {
    alias: { '@': path.resolve(__dirname, 'src') },
  },
})
