// Generated by scripts/gen_frontend.py. Edit that, not this file.

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import frappeui from 'frappe-ui/vite'
import path from 'node:path'

// frappe-ui's plugin owns the parts that are easy to get subtly wrong: it
// proxies /api, /app, /assets, /files and /private to the bench it detects from
// common_site_config.json, and it emits ../oneapp_control/www/<route>.html so the SPA is
// served by Frappe itself. Hand-rolling any of that is how the two apps drift.
export default defineConfig({
  plugins: [
    frappeui({
      frontendRoute: '/admin',
      // Given explicitly rather than inferred. frappe-ui derives these by
      // walking up for a bench layout (a directory with both sites/ and apps/),
      // which exists on Frappe Cloud but not in this monorepo — so inference
      // returns null here and the production build fails with
      // "indexHtmlPath is required". Stating them makes the build identical
      // everywhere: monorepo, bench, and CI.
      buildConfig: {
        outDir: path.resolve(__dirname, '../oneapp_control/public/frontend'),
        indexHtmlPath: '../oneapp_control/www/admin.html',
      },
      frappeTypes: {
        input: {
  'oneapp_control': [
    'Tenant',
    'Shard',
    'Plan',
    'Subscription',
    'Provisioning Job',
    'Credit Ledger Entry',
    'OneApp App'
  ]
},
      },
    }),
    vue(),
  ],
  resolve: {
    alias: { '@': path.resolve(__dirname, 'src') },
  },
})
