// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * The per-browser conveniences, and the one door they go through.
 *
 * `localStorage` was written from seven places with seven key shapes, and the
 * question that decides whether something belongs in it was never asked out
 * loud. It is this: **would I want to send this to a colleague?** If yes it
 * belongs in the URL or in a saved view, because it is part of what I am
 * looking at. If no it belongs here, because it is a habit of mine and my
 * browser is where my habits live.
 *
 * Drive's order failed that test and moved to the URL — a link sent to a
 * colleague used to arrive in whatever order *their* browser last used, while
 * a screen link arrived exactly as sent. What is left here passes it: a rail
 * I collapsed, a pane I dragged narrower, the last thing I picked in a field.
 *
 * Every key is declared below, so the guard can check that what is stored is
 * the kind of thing this is for. Reads and writes both go through here, which
 * is also where the `try` lives: storage can be off, full, or blocked, and on
 * every one of those the right answer is to forget rather than to throw.
 *
 * `docs/UNIFICATION.md` §C4, rail 19.
 */

/**
 * What may be remembered, and why each is a habit rather than a place.
 *
 * A key is a prefix: `remember('drive.grid')` and
 * `remember('field.last', space, screen, fieldname)` both name the same
 * declared thing, and the parts after it say whose.
 */
export const KEYS = Object.freeze({
  'rail.shut': 'Whether I keep the space rail collapsed.',
  'drive.grid': 'Whether I look at files as thumbnails or as a list.',
  'drive.order': "The order I last put a Drive place in. A fallback: the URL wins, and a link that names one arrives in it.",
  'record.surface': 'Whether I open records in a pane or full width, per screen.',
  'child.columns': 'Which columns I keep on a child table.',
  'field.last': 'The last thing I picked in a field that asks to remember.',
  'pane.width': 'How wide I dragged a pane.',
  'sound': 'Whether I want the notification sound.',
})

const PREFIX = 'onespace'

/** The full key: the declared name, then whatever narrows it. */
function slot(key, ...parts) {
  if (!Object.hasOwn(KEYS, key)) {
    throw new Error(
      `Nothing may be remembered under "${key}". Declare it in lib/url/remember.js, `
      + 'and say there why it is a habit rather than a place.',
    )
  }
  return [PREFIX, key, ...parts.filter((one) => one !== undefined && one !== null)].join(':')
}

/**
 * What was remembered, or `null`.
 *
 * Never throws, and `null` is the only way it says no: a private window,
 * cleared site data and a full quota all mean "nothing was remembered", which
 * is true and is the only useful answer. The caller supplies its own default
 * with `??`, because the default is a fact about that surface rather than
 * about storage.
 */
export function recall(key, ...parts) {
  try {
    return window.localStorage.getItem(slot(key, ...parts))
  } catch {
    return null
  }
}

/** Remember it. Forgetting is the whole cost of failing, so nothing is said. */
export function remember(key, value, ...parts) {
  try {
    window.localStorage.setItem(slot(key, ...parts), String(value))
  } catch {
    // Storage off, or full. The next visit starts from the default.
  }
}

/** Stop remembering it. */
export function forget(key, ...parts) {
  try {
    window.localStorage.removeItem(slot(key, ...parts))
  } catch {
    // Already gone, as far as anybody can tell.
  }
}

/** The same three, for something that is not a string. */
export function recallJson(key, ...parts) {
  const held = recall(key, ...parts)
  if (held === null) return null
  try {
    return JSON.parse(held)
  } catch {
    return null
  }
}

export const rememberJson = (key, value, ...parts) =>
  remember(key, JSON.stringify(value), ...parts)
