<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <!-- Mobile: no rail slot exists on MobileShell, so the app switcher moves into
       a sheet reachable from the bottom bar. Without it the rail's whole job —
       moving between apps — is simply missing below 768px. -->
  <MobileShell v-if="isMobile">
    <slot />

    <template #nav>
      <MobileNav>
        <MobileNavItem
          v-for="item in navItems"
          :key="item.label"
          :label="item.label"
          :icon="item.icon"
          :to="item.to"
          :active="item.active"
        />
        <MobileNavItem
          v-if="apps.length > 1"
          label="Apps"
          icon="lucide-grid-2x2"
          :active="showSwitcher"
          @click="showSwitcher = true"
        />
      </MobileNav>
    </template>
  </MobileShell>

  <DesktopShell v-else :scroll="scroll">
    <template v-if="apps.length" #rail>
      <Rail class="border-r border-outline-gray-1">
        <RailItem
          v-for="app in apps"
          :key="app.key"
          :label="app.label"
          :description="app.description"
          :active="app.key === activeApp"
          :to="app.to"
          variant="tile"
          @click="$emit('select-app', app.key)"
        >
          <Avatar :label="app.label" :image="app.image" size="lg" shape="square" class="size-7" />
        </RailItem>

        <div class="mt-auto flex flex-col items-center gap-2.5 pt-3">
          <slot name="rail-footer" />
        </div>
      </Rail>
    </template>

    <template v-if="$slots.sidebar" #sidebar>
      <slot name="sidebar" />
    </template>

    <slot />
  </DesktopShell>

  <!-- Sheet rather than a dropdown: on a phone this is the primary way to change
       context, and a sheet gives it a touch target per app instead of a menu row. -->
  <BottomSheet v-model="showSwitcher" title="Apps">
    <div class="flex flex-col gap-1 p-2 pb-6">
      <router-link
        v-for="app in apps"
        :key="app.key"
        :to="app.to"
        class="flex items-center gap-3 rounded p-2 active:bg-surface-gray-2"
        @click="showSwitcher = false"
      >
        <Avatar :label="app.label" :image="app.image" size="xl" shape="square" />
        <span class="min-w-0 flex-1 truncate text-base text-ink-gray-8">{{ app.label }}</span>
        <Icon
          v-if="app.key === activeApp"
          name="lucide-check"
          class="size-4 shrink-0 text-ink-gray-6"
        />
      </router-link>
    </div>
  </BottomSheet>
</template>

<script setup>
import { ref } from 'vue'
import {
  Avatar,
  BottomSheet,
  DesktopShell,
  Icon,
  MobileNav,
  MobileNavItem,
  MobileShell,
  Rail,
  RailItem,
} from '@/ui'
import { useIsMobile } from '@/lib/screen'

defineProps({
  /**
   * Rail entries. Each is { key, label, to, image?, description? }.
   * Empty renders no rail at all — a single-app surface should not show a
   * one-item switcher.
   */
  apps: { type: Array, default: () => [] },
  activeApp: { type: String, default: '' },
  /** Bottom-bar destinations on mobile: { label, icon, to, active? }. */
  navItems: { type: Array, default: () => [] },
  /** false when inner panes own their scroll — a list/detail split, say. */
  scroll: { type: Boolean, default: true },
})

defineEmits(['select-app'])

defineSlots()

const isMobile = useIsMobile()
const showSwitcher = ref(false)
</script>
