<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <!--
    Mobile navigation, and what decides what goes where.

    MobileNav is a grid: every item takes an equal share of the bar, so five is
    the practical ceiling before the labels stop being readable on a 360px
    phone. A sidebar can hold twenty entries; a bottom bar cannot, and picking
    the first twenty is not a design.

    So the last slot is always the same thing — the account avatar, opening a
    sheet — and the four before it are the app's primary destinations. Anything
    a surface declares past the fourth, or marks `primary: false`, falls into
    that sheet rather than being dropped. The sheet is also the only place a
    phone can reach what the desktop keeps in the rail footer and the sidebar
    foot: the app switcher, settings, appearance, the account itself.

    This mirrors frappe-ui's own MobileNav example, whose last item is a "You"
    avatar rather than another destination.
  -->
  <MobileShell v-if="isMobile">
    <slot />

    <template #nav>
      <MobileNav>
        <MobileNavItem
          v-for="item in primaryNav"
          :key="item.label"
          :label="item.label"
          :icon="item.icon"
          :to="item.to"
          :active="item.active"
        >
          <!-- The default slot replaces the icon, not the label, so a badged
               item still reads the same as its neighbours. -->
          <template v-if="item.badge" #default="{ active }">
            <span class="relative">
              <Icon
                :name="item.icon"
                class="size-6"
                :class="active ? 'text-ink-gray-8' : 'text-ink-gray-5'"
              />
              <Badge
                class="absolute -right-2.5 -top-1 scale-90"
                :theme="item.badge.theme"
                :label="item.badge.label"
                variant="subtle"
              />
            </span>
          </template>
        </MobileNavItem>

        <MobileNavItem label="More" :active="showMenu" @click="showMenu = true">
          <template #default="{ active }">
            <Avatar
              :label="user.name || user.email || 'Account'"
              :image="user.avatar"
              size="md"
              :class="active ? 'ring-2 ring-outline-gray-4' : ''"
            />
          </template>
        </MobileNavItem>
      </MobileNav>
    </template>
  </MobileShell>

  <DesktopShell v-else :scroll="scroll">
    <template v-if="apps.length" #rail>
      <Rail class="border-r border-outline-gray-1">
        <RailItem
          v-for="app in apps"
          :key="app.key"
          :label="app.label"
          :description="app.description"
          :active="app.key === activeApp"
          :to="app.to"
          variant="tile"
          @click="$emit('select-app', app.key)"
        >
          <Avatar :label="app.label" :image="app.image" size="lg" shape="square" class="size-7" />
        </RailItem>

        <div class="mt-auto flex flex-col items-center gap-2.5 pt-3">
          <slot name="rail-footer" />
        </div>
      </Rail>
    </template>

    <template v-if="$slots.sidebar" #sidebar>
      <slot name="sidebar" />
    </template>

    <slot />
  </DesktopShell>

  <!-- Sheet rather than a dropdown: on a phone this is the primary way to change
       context, and a sheet gives it a touch target per row instead of a menu row. -->
  <!-- v-model:open, not v-model. BottomSheet's prop is `open`, so a bare
       v-model binds a `modelValue` it never reads and the sheet never opens. -->
  <BottomSheet v-model:open="showMenu" title="Menu">
    <div class="flex flex-col gap-5 p-3 pb-8">
      <div class="flex items-center gap-3 px-1">
        <Avatar
          :label="user.name || user.email || 'Account'"
          :image="user.avatar"
          size="2xl"
        />
        <div class="min-w-0 flex-1">
          <p class="truncate text-base-medium text-ink-gray-8">
            {{ user.name || user.email || 'Account' }}
          </p>
          <p v-if="user.subtitle || user.email" class="truncate text-p-sm text-ink-gray-5">
            {{ user.subtitle || user.email }}
          </p>
        </div>
      </div>

      <section v-if="apps.length > 1">
        <p class="px-1 pb-1 text-p-sm text-ink-gray-5">{{ appsLabel }}</p>
        <router-link
          v-for="app in apps"
          :key="app.key"
          :to="app.to"
          class="flex items-center gap-3 rounded-4 p-2 active:bg-surface-gray-2"
          @click="showMenu = false"
        >
          <Avatar :label="app.label" :image="app.image" size="xl" shape="square" />
          <span class="min-w-0 flex-1 truncate text-base text-ink-gray-8">{{ app.label }}</span>
          <Icon
            v-if="app.key === activeApp"
            name="lucide-check"
            class="size-4 shrink-0 text-ink-gray-6"
          />
        </router-link>
      </section>

      <section v-if="overflowNav.length">
        <p class="px-1 pb-1 text-p-sm text-ink-gray-5">More pages</p>
        <router-link
          v-for="item in overflowNav"
          :key="item.label"
          :to="item.to"
          class="flex items-center gap-3 rounded-4 p-2 active:bg-surface-gray-2"
          @click="showMenu = false"
        >
          <Icon :name="item.icon" class="size-4 shrink-0 text-ink-gray-7" />
          <span class="min-w-0 flex-1 truncate text-base text-ink-gray-8">{{ item.label }}</span>
          <Badge
            v-if="item.badge"
            :theme="item.badge.theme"
            :label="item.badge.label"
            variant="subtle"
          />
        </router-link>
      </section>

      <section v-if="menuItems.length" class="flex flex-col gap-1">
        <Button
          v-for="item in menuItems"
          :key="item.label"
          variant="ghost"
          class="!h-11 w-full !justify-start !px-2"
          :icon-left="item.icon"
          :label="item.label"
          @click="run(item)"
        />
      </section>

      <div>
        <p class="px-1 pb-1.5 text-p-sm text-ink-gray-5">Appearance</p>
        <!-- Three buttons, not a switch: a two-state control cannot express
             "follow the system", and one tap still picks any of the three. -->
        <TabButtons v-model="scheme" :options="tabOptions" fluid />
      </div>

      <Button
        class="w-full"
        variant="subtle"
        theme="red"
        icon-left="lucide-log-out"
        label="Log out"
        @click="logout"
      />
    </div>
  </BottomSheet>
</template>

<script setup>
import { computed, ref } from 'vue'
import {
  Avatar,
  Badge,
  BottomSheet,
  Button,
  DesktopShell,
  Icon,
  MobileNav,
  MobileNavItem,
  MobileShell,
  Rail,
  RailItem,
  TabButtons,
} from '@/ui'
import { useAppearance } from '@/lib/appearance'
import { useIsMobile } from '@/lib/screen'

const props = defineProps({
  /**
   * Rail entries. Each is { key, label, to, image?, description? }.
   * Empty renders no rail at all — a single-app surface should not show a
   * one-item switcher.
   */
  apps: { type: Array, default: () => [] },
  activeApp: { type: String, default: '' },
  /** Heading the mobile sheet gives the rail's entries. */
  appsLabel: { type: String, default: 'Apps' },
  /**
   * Every destination this surface has, in sidebar order:
   * { label, icon, to, active?, badge?, primary? }.
   *
   * The first four reach the bottom bar; the rest, and anything marked
   * `primary: false`, go to the More sheet. Declared once per surface in
   * `lib/nav.js` so the bar and the sidebar cannot drift.
   */
  navItems: { type: Array, default: () => [] },
  /**
   * Actions that live in the rail footer or the sidebar foot on a desktop,
   * e.g. Settings. A phone has neither, so they appear in the More sheet.
   */
  menuItems: { type: Array, default: () => [] },
  /** Identity for the bottom bar's avatar: { name, email, avatar, subtitle }. */
  user: { type: Object, default: () => ({}) },
  /** false when inner panes own their scroll — a list/detail split, say. */
  scroll: { type: Boolean, default: true },
})

defineEmits(['select-app'])

defineSlots()

const isMobile = useIsMobile()
const showMenu = ref(false)

// Four, because the avatar always takes the fifth. `primary: false` opts an
// item out without reordering the sidebar to get it out of the way.
const PRIMARY_SLOTS = 4

const primaryNav = computed(() =>
  props.navItems.filter((item) => item.primary !== false).slice(0, PRIMARY_SLOTS),
)

const overflowNav = computed(() =>
  props.navItems.filter((item) => !primaryNav.value.includes(item)),
)

const { scheme, tabOptions } = useAppearance()

function run(item) {
  showMenu.value = false
  item.onClick?.()
}

// Frappe's own logout clears the session cookie server-side; a client-side
// redirect alone would leave the session valid.
function logout() {
  window.location.href = '/api/method/logout'
}
</script>
