<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <div class="grid place-items-center px-6 py-16 text-center">
    <div class="max-w-sm">
      <Icon v-if="icon" :name="icon" class="mx-auto mb-3 size-6 text-ink-gray-4" />
      <p class="text-base-medium text-ink-gray-8">{{ title }}</p>
      <p v-if="description" class="mt-1.5 text-p-base text-ink-gray-6">
        {{ description }}
      </p>
      <div v-if="$slots.action" class="mt-4"><slot name="action" /></div>
    </div>
  </div>
</template>

<script setup>
import { Icon } from '@/ui'

defineProps({
  title: { type: String, required: true },
  description: { type: String, default: '' },
  icon: { type: String, default: '' },
})
</script>
