<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <component :is="as" data-slot="panel" :class="look">
    <slot />
  </component>
</template>

<script setup>
import { computed } from 'vue'

//: No warning. Named so the template's own comparison is not a bare string.
const NEUTRAL = 'neutral'

// The ground, and the border that goes with it. One map rather than two props,
// because a red panel with a grey border is not a thing anybody wants and
// making it expressible only means somebody eventually writes it.
//
// `base` is the page's own white. `raised` is the surface a shadow is allowed
// to sit on — see the elevation note below, and `lib/shell/theme.js` for why
// dark mode steps *lighter* rather than darker. `sunken` is a well inside a
// panel: a settings group, a read-only preview, the thing that is part of the
// page rather than on top of it.
const GROUND = {
  base: 'border-outline-gray-2 bg-surface-base',
  raised: 'border-outline-gray-2 bg-surface-elevation-2',
  sunken: 'border-outline-gray-2 bg-surface-gray-1',
  amber: 'border-outline-amber-2 bg-surface-amber-1',
  red: 'border-outline-red-2 bg-surface-red-1',
}

// Four rooms and a bar. `bar` is not a smaller `tight`: a row of controls is
// wider than it is tall and wants asymmetric padding, and seven call sites had
// each derived their own version of that — `px-2.5 py-2`, `px-3 py-2.5`,
// `px-4 py-2`, `px-3 py-2`.
const PAD = {
  none: '',
  tight: 'p-3',
  normal: 'p-4',
  loose: 'p-5',
  bar: 'px-3 py-2',
}

// The names from `scripts/spa/build.py`. A panel is the commonest thing that
// floats, so the height is a prop here rather than a class at the call site.
const ELEVATION = {
  flat: '',
  raised: 'shadow-raised',
  floating: 'shadow-floating',
  over: 'shadow-over',
}

const props = defineProps({
  // The literal lists again rather than `value in GROUND`: `defineProps` is
  // hoisted above the component's own scope, so a validator that closes over a
  // local const is a runtime reference error — `vue/valid-define-props` is
  // what catches it, and it caught this.
  ground: {
    type: String,
    default: 'base',
    validator: (value) => ['base', 'raised', 'sunken', 'amber', 'red'].includes(value),
  },
  pad: {
    type: String,
    default: 'normal',
    validator: (value) => ['none', 'tight', 'normal', 'loose', 'bar'].includes(value),
  },
  elevation: {
    type: String,
    default: 'flat',
    validator: (value) => ['flat', 'raised', 'floating', 'over'].includes(value),
  },
  // A warning or a failure, which takes the ground over rather than sitting
  // beside it — an amber panel is amber all the way through.
  tone: {
    type: String,
    default: 'neutral',
    validator: (value) => ['neutral', 'amber', 'red'].includes(value),
  },
  // A panel is sometimes a `<section>`, an `<aside>` or a `<form>`. The
  // default is the one that claims nothing.
  as: { type: String, default: 'div' },
})

// Resolved here rather than in the template, and that is not only tidiness:
// `tests/token_audit.py` reads every string literal inside a `:class`
// expression as a class list, so `tone === 'neutral' ? …` in the markup makes
// `neutral` a utility that emits no CSS and fails the audit. The scan is
// right to be that blunt — a class hidden in an expression is how a retired
// token drew a transparent column for a week.
const look = computed(() => [
  'rounded-6 border',
  GROUND[props.tone === NEUTRAL ? props.ground : props.tone],
  PAD[props.pad],
  ELEVATION[props.elevation],
])
</script>
