<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <component
    :is="element"
    :to="to || undefined"
    :href="href || undefined"
    :type="element === 'button' ? 'button' : undefined"
    :aria-current="open ? 'true' : undefined"
    data-slot="row"
    :class="look"
  >
    <slot v-if="layout === BARE" />
    <template v-else>
      <span v-if="$slots.lead" class="flex shrink-0 items-center">
        <slot name="lead" />
      </span>
      <span class="min-w-0 flex-1"><slot /></span>
      <span v-if="$slots.trail" class="flex shrink-0 items-center gap-1">
        <slot name="trail" />
      </span>
    </template>
  </component>
</template>

<script setup>
import { computed, useAttrs } from 'vue'
import { RouterLink } from 'vue-router'

import { rowState } from '@/lib/rowstate'

//: The escape hatch, named so the template compares against a const rather
//: than a bare string — `tests/token_audit.py` reads every string literal
//: inside a `:class` or a template expression as a class name.
const BARE = 'bare'

// How the row lays itself out, and there are only two because there were only
// ever two shapes under the seventeen hand-rolled ones.
//
// `row` is fifteen of them: something at the start, something in the middle
// that is allowed to run out of room, something at the end. `bare` is the
// other two — Mail's thread, which is two stacked lines each with their own
// start and end, and anything else that is genuinely not a line. `bare`
// contributes no layout at all, so the caller's own `flex flex-col` cannot
// lose a fight with the component's `items-center`, which is what a third
// layout prop would have guaranteed.
const LAYOUT = {
  row: 'flex w-full gap-3 text-start',
  bare: 'w-full text-start',
}

//: Where the lead and the trail sit against a body that wrapped. `start` is
//: for the rows whose body is two or three lines — a notification, a finding.
const ALIGN = { center: 'items-center', start: 'items-start' }

// Three rooms, down from the seven spellings the call sites had between them
// (`px-2 py-1.5`, `px-2.5 py-2`, `px-3 py-2`, `px-3 py-2.5`, `px-4 py-2`,
// `px-4 py-2.5`, `px-4 py-3`). The two-pixel differences were nobody's
// decision; they are what happens when each surface picks its own.
const PAD = {
  none: '',
  tight: 'px-2 py-1.5',
  normal: 'px-3 py-2.5',
  loose: 'px-4 py-3',
}

// What separates one row from the next, and it is one question with three
// answers rather than two independent props. A list either rules between its
// rows or floats them apart; doing both is how a settings list ended up with
// a hairline *and* a gap, which reads as two lists.
const EDGE = {
  divider: 'border-b border-outline-gray-1 last:border-0',
  // The row is its own tile. The gap comes from the parent's `gap-*`, because
  // the parent is the only thing that knows how many there are.
  rounded: 'rounded-4',
  none: '',
}

const props = defineProps({
  // Where it goes. A row that is a place is a link — that is what makes the
  // back button work and a reload land in the same row — so `to` is the first
  // thing to reach for and `@click` is for rows that do something instead.
  to: { type: [String, Object], default: null },
  href: { type: String, default: '' },
  //: Overrides the element entirely, for the caller that needs an `<li>`.
  as: { type: [String, Object], default: null },

  // The five states, straight through to `rowState`. `selected` is the set
  // being acted on, `open` is the one in the pane beside the list, and the
  // last two are the drag.
  selected: { type: Boolean, default: false },
  //: The keyboard is on it while the caret is elsewhere — a picker's list.
  active: { type: Boolean, default: false },
  open: { type: Boolean, default: false },
  lifted: { type: Boolean, default: false },
  drop: { type: Boolean, default: false },

  // Literal arrays rather than `value in PAD`: `defineProps` is hoisted above
  // the component's scope, so a validator closing over a local const is a
  // reference error at runtime. Panel.vue learned this first.
  layout: {
    type: String,
    default: 'row',
    validator: (value) => ['row', 'bare'].includes(value),
  },
  align: {
    type: String,
    default: 'center',
    validator: (value) => ['center', 'start'].includes(value),
  },
  pad: {
    type: String,
    default: 'normal',
    validator: (value) => ['none', 'tight', 'normal', 'loose'].includes(value),
  },
  edge: {
    type: String,
    default: 'divider',
    validator: (value) => ['divider', 'rounded', 'none'].includes(value),
  },

  //: A row that is decoration rather than a line in a list — a header, a
  //: total. Off is rare enough to be the thing you say.
  hover: { type: Boolean, default: true },

  //: What is behind it. `overlay` is a row over a photograph or a brand
  //: colour, where a grey fill is mud — see `lib/rowstate.js`.
  ground: {
    type: String,
    default: 'surface',
    validator: (value) => ['surface', 'overlay'].includes(value),
  },
})

const attrs = useAttrs()

/**
 * What element this actually is, worked out rather than asked for.
 *
 * A row that navigates is a link, a row that acts is a button, and a row that
 * does neither is a `div` — and getting that wrong is not cosmetic: the
 * hand-rolled ones included clickable `<div>`s, which the keyboard cannot
 * reach and a screen reader does not announce. Deriving it means no caller
 * can get it wrong by forgetting.
 */
const element = computed(() => {
  if (props.as) return props.as
  if (props.to) return RouterLink
  if (props.href) return 'a'
  return attrs.onClick ? 'button' : 'div'
})

/**
 * Whether the row itself can hold the keyboard — which is not the same
 * question as whether it reacts to a pointer, and conflating the two is how
 * this was got wrong twice.
 *
 * The focus ring belongs only to a row that can actually be focused: drawn on
 * a `<li>` it is a promise no tab stop keeps. The *hover* belongs to almost
 * every row, including the ones that are containers for their own controls —
 * a file line with a link and a delete button in it is still one line you are
 * about to act on, and highlighting it is what makes a column of forty
 * scannable. So hover is a prop with a default and focus is derived.
 */
const interactive = computed(() => Boolean(props.to || props.href || attrs.onClick))

const look = computed(() => [
  rowState({
    selected: props.selected,
    active: props.active,
    open: props.open,
    lifted: props.lifted,
    drop: props.drop,
    hover: props.hover,
    focus: interactive.value,
    ground: props.ground,
  }),
  LAYOUT[props.layout],
  props.layout === BARE ? '' : ALIGN[props.align],
  PAD[props.pad],
  EDGE[props.edge],
])
</script>
