<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <!--
    SettingsRow + Select, which is what SettingsRow is for: a label and a
    description on the left, one compact control on the right.

    Not ThemeSwitcher. frappe-ui 1.0 marks it `@deprecated` — "Use `Select` with
    `useColorScheme` instead" — and it calls warnDeprecated on every render.
  -->
  <SettingsRow
    title="Appearance"
    description="Light, dark, or matching your system."
  >
    <Select v-model="scheme" :options="SCHEMES" />
  </SettingsRow>
</template>

<script setup>
import { computed } from 'vue'
import { Select, SettingsRow, useColorScheme } from '@/ui'

// Three states, not a toggle. A binary switch cannot express 'follow the
// system', so a user who wants that has to keep changing it by hand twice a day.
const SCHEMES = [
  { label: 'Light', value: 'light' },
  { label: 'Dark', value: 'dark' },
  { label: 'System', value: 'system' },
]

const { colorScheme, setColorScheme } = useColorScheme()

const scheme = computed({
  get: () => colorScheme.value,
  // colorScheme is readonly on purpose: the ref is only a third of the state,
  // alongside the <html> attribute and the stored value. setColorScheme moves
  // all three together.
  set: (value) => setColorScheme(value),
})
</script>
