<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <ThemeSwitcher
    v-model="scheme"
    label="Appearance"
    description="Light, dark, or matching your system."
  />
</template>

<script setup>
import { computed } from 'vue'
import { ThemeSwitcher, useColorScheme } from '@/ui'

// Three states, not a toggle. A binary switch cannot express 'follow the
// system', so a user who wants that has to keep changing it by hand twice a day.
const { colorScheme, setColorScheme } = useColorScheme()

const scheme = computed({
  get: () => colorScheme.value,
  // colorScheme is readonly on purpose: the ref is only a third of the state,
  // alongside the <html> attribute and the stored value. setColorScheme moves
  // all three together.
  set: (value) => setColorScheme(value),
})
</script>
