<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <!--
    SettingsRow + Select, which is what SettingsRow is for: a label and a
    description on the left, one compact control on the right.

    Not ThemeSwitcher. frappe-ui 1.0 marks it `@deprecated` — "Use `Select` with
    `useColorScheme` instead" — and it calls warnDeprecated on every render.
  -->
  <SettingsRow
    title="Appearance"
    description="Light, dark, or matching your system."
  >
    <Select v-model="scheme" :options="selectOptions" />
  </SettingsRow>
</template>

<script setup>
import { Select, SettingsRow } from '@/ui'
import { useAppearance } from '@/lib/appearance'

// Three states, not a toggle. A binary switch cannot express 'follow the
// system', so a user who wants that has to keep changing it by hand twice a day.
const { scheme, selectOptions } = useAppearance()
</script>
