<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <div>
    <div class="flex items-baseline justify-between gap-2">
      <span class="text-p-sm text-ink-gray-6">{{ label }}</span>
      <span class="shrink-0 text-p-sm tabular-nums" :class="valueClass">
        {{ formatted }}
      </span>
    </div>
    <Progress class="mt-1.5" size="sm" :value="percent" :class="barClass" />
    <p v-if="usage?.exceeded" class="mt-1.5 text-p-sm text-ink-red-3">
      {{ exceededHint }}
    </p>
    <p v-else-if="usage?.warn" class="mt-1.5 text-p-sm text-ink-amber-3">
      Approaching the limit.
    </p>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { Progress } from '@/ui'

const props = defineProps({
  label: { type: String, required: true },
  usage: { type: Object, default: null },
  // 'bytes' for storage and database, 'count' for seats.
  format: { type: String, default: 'bytes' },
  exceededHint: { type: String, default: 'At the limit. Free some space or add more.' },
})

const percent = computed(() => Math.min((props.usage?.fraction || 0) * 100, 100))

// Progress has no `theme`: its fill is always `bg-surface-gray-10`, so the
// colour has to be applied from outside. `class` falls through to the root, and
// the fill is the element inside `role="progressbar"` — `!` because the
// component's own background class is on that same element.
const barClass = computed(() => {
  if (props.usage?.exceeded) return '[&_[role=progressbar]>*]:!bg-surface-red-6'
  if (props.usage?.warn) return '[&_[role=progressbar]>*]:!bg-surface-amber-5'
  return ''
})

const valueClass = computed(() => {
  if (props.usage?.exceeded) return 'text-ink-red-3'
  if (props.usage?.warn) return 'text-ink-amber-3'
  return 'text-ink-gray-7'
})

function bytes(value) {
  if (!value) return '0 B'
  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.min(Math.floor(Math.log(value) / Math.log(1024)), units.length - 1)
  return `${(value / 1024 ** i).toFixed(i === 0 ? 0 : 1)} ${units[i]}`
}

const formatted = computed(() => {
  const u = props.usage
  if (!u) return ''
  if (!u.quota) return props.format === 'bytes' ? bytes(u.used) : String(u.used)
  return props.format === 'bytes'
    ? `${bytes(u.used)} of ${bytes(u.quota)}`
    : `${u.used} of ${u.quota}`
})
</script>
