<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <!-- `side` + `align`, not `placement`: frappe-ui removed `placement` in 1.0
       and warns about it in dev, so the menu was never positioned. -->
  <Dropdown :options="options" side="top" align="start" class="w-full">
    <Button variant="ghost" class="!h-11 w-full !justify-start !px-2">
      <template #prefix>
        <Avatar :label="displayName" :image="avatar" size="md" />
      </template>
      <span class="min-w-0 flex-1 text-left">
        <span class="block truncate text-base text-ink-gray-8">{{ displayName }}</span>
        <span v-if="subtitle" class="block truncate text-xs text-ink-gray-5">
          {{ subtitle }}
        </span>
      </span>
      <template #suffix>
        <Icon name="lucide-chevron-up" class="size-4 text-ink-gray-5" />
      </template>
    </Button>
  </Dropdown>
</template>

<script setup>
import { computed } from 'vue'
import { Avatar, Button, Dropdown, Icon } from '@/ui'

const props = defineProps({
  name: { type: String, default: '' },
  email: { type: String, default: '' },
  avatar: { type: String, default: '' },
  subtitle: { type: String, default: '' },
  // Entries shown above the standard ones, e.g. Settings for an operator.
  extra: { type: Array, default: () => [] },
})

const displayName = computed(() => props.name || props.email || 'Account')

// Deliberately no light/dark toggle here. A binary switch cannot express
// 'follow the system', so anyone who wants that ends up flipping it by hand
// twice a day. Appearance is a three-way choice and lives in settings, next to
// every other preference — see ThemeSetting.vue.
const options = computed(() => [
  ...props.extra,
  {
    label: 'Log out',
    icon: 'lucide-log-out',
    // Frappe's own logout clears the session cookie server-side; a client-side
    // redirect alone would leave the session valid.
    onClick: () => {
      window.location.href = '/api/method/logout'
    },
  },
])
</script>
