<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <!-- `side` + `align`, not `placement`: frappe-ui removed `placement` in 1.0
       and warns about it in dev, so the menu was never positioned. -->
  <Dropdown :options="options" side="top" align="start" class="w-full">
    <!-- icon-right, not a #suffix holding an <Icon>: Button declares the prop
         and renders it at the library's own size and tone. The #prefix stays a
         slot because an Avatar is not something an icon prop can express. -->
    <Button
      variant="ghost"
      icon-right="lucide-chevron-up"
      class="!h-11 w-full !justify-start !px-2"
    >
      <template #prefix>
        <Avatar :label="displayName" :image="avatar" size="md" />
      </template>
      <span class="min-w-0 flex-1 text-left">
        <span class="block truncate text-base text-ink-gray-8">{{ displayName }}</span>
        <span v-if="subtitle" class="block truncate text-xs text-ink-gray-5">
          {{ subtitle }}
        </span>
      </span>
    </Button>
  </Dropdown>
</template>

<script setup>
import { computed } from 'vue'
import { Avatar, Button, Dropdown } from '@/ui'
import { useAppearance } from '@/lib/appearance'

const props = defineProps({
  name: { type: String, default: '' },
  email: { type: String, default: '' },
  avatar: { type: String, default: '' },
  subtitle: { type: String, default: '' },
  // Entries shown above the standard ones, e.g. Settings for an operator.
  extra: { type: Array, default: () => [] },
})

const displayName = computed(() => props.name || props.email || 'Account')

// Appearance sits here as well as in settings: it is the preference people
// change most often, and hunting for it behind a dialog is the slow path.
//
// Three rows in a group rather than a switch. A two-state control cannot
// express "follow the system", so anyone who wants that ends up flipping it by
// hand twice a day — and a row is the same single tap a switch would be, with
// the current choice visible instead of inferred. `selected` is a
// MenuBaseOption field, so the tick is the library's own.
const { menuGroup } = useAppearance()

const options = computed(() => [
  ...props.extra,
  menuGroup.value,
  {
    label: 'Log out',
    icon: 'lucide-log-out',
    // Frappe's own logout clears the session cookie server-side; a client-side
    // redirect alone would leave the session valid.
    onClick: () => {
      window.location.href = '/api/method/logout'
    },
  },
])
</script>
