// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Boot data injected by frappe-ui's vite plugin.
 *
 * The plugin's jinjaBootData sub-plugin writes the www page's `boot` context
 * onto `window`, so whatever the page controller puts there is available before
 * the app mounts. Everything here degrades to a sane default, because the dev
 * server serves index.html without Jinja and would otherwise crash on boot.
 */

// The plugin emits `window["<key>"] = <value>` for each key in the page's boot
// context — so `boot.site_name` lands as `window.site_name`, not under a `boot`
// object. Reading window.boot would silently yield undefined and leave the
// socket pointed at the wrong host.
const read = (key, fallback) => (window[key] !== undefined ? window[key] : fallback)

export const siteName = read('site_name', window.location.hostname)
export const socketioPort = read('socketio_port', 9000)
export const csrfToken = read('csrf_token', null)
export const sessionUser = read('user', 'Guest')
// Frappe stores datetimes in the system timezone, not the reader's. `dayjsLocal`
// converts between the two, but only once it has been told which system zone to
// convert from — see main.js. Empty is the safe default: dayjsLocal then behaves
// exactly like dayjs rather than shifting by a guess.
export const systemTimezone = read('system_timezone', '')
// Two different questions, and they used to be one. `import.meta.env.DEV` says
// Vite is serving the app; `dev_server` says the site has nothing in front of
// it routing `/socket.io/` to the socketio port. A built SPA served by a bench
// is the case where the first is false and the second is true — and the socket
// went same-origin and 404ed on every local run, which is why realtime was
// "not covered locally" for as long as it was.
export const isDev = import.meta.env.DEV
export const devServer = !!read('dev_server', 0) || import.meta.env.DEV
// What this workspace looks like: `{ accent, favicon, splash }`, built by
// `oneapp_core/branding.py`. All three are wanted before the first paint — the
// accent so no button is drawn in the default colour and then repainted, the
// favicon so the tab does not visibly change — which is why they ride the boot
// payload rather than the session resource.
export const brand = read('brand', {})
// Which language to draw in, and therefore which way. The reader's own, or the
// workspace's — `www/one.py` decides; this only has to know the answer before
// the first paint, because changing it later moves the whole layout.
export const lang = read('lang', 'en')
// Who the assistant is: `{ name, avatar, tone, personality }`, built by
// `oneapp_core/ai/settings.py`. Here for the same reason the favicon is — the
// chat rail and the panel header name it before anything is fetched, and a
// header that says "Assistant" for a moment and then says something else is a
// visible flicker. `lib/shell/assistant.js` makes it reactive from here.
export const assistant = read('assistant', {})

export default {
  siteName,
  socketioPort,
  csrfToken,
  sessionUser,
  systemTimezone,
  isDev,
  devServer,
  brand,
  lang,
  assistant,
}
