// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Dates in the reader's language.
 *
 * A page can be translated down to the last button and still say the age of
 * every row in English, because "8 days ago" is not a msgid: it is built by
 * dayjs's `relativeTime` plugin out of a locale of its own. This loads that
 * locale, once, before the app mounts.
 *
 * Its own module rather than a corner of `translate.js`, which is deliberately
 * free of imports — it is read by a test that runs it under node, where `@/ui`
 * means nothing.
 */

import { dayjs } from '@/ui'

/**
 * The languages dayjs has to be told about, and how.
 *
 * "8 days ago" is not translated by the catalogue: it is built by dayjs's
 * `relativeTime` plugin out of a locale that has to be loaded, and without one
 * every row of every list says its age in English on an otherwise Arabic
 * screen. Named one by one rather than built from the language — the import
 * path has to be a literal or the bundler cannot see which locales to ship, and
 * it would either bundle all one hundred and thirty or none.
 */
const DATE_LOCALES = {
  ar: () => import('dayjs/esm/locale/ar'),
  de: () => import('dayjs/esm/locale/de'),
}

/**
 * Teach dayjs the reader's language. English needs nothing — it is the default
 * — and a language we have no locale for keeps English dates rather than
 * failing, which is the same bargain `loadTranslations` makes.
 */
export async function loadDates(lang) {
  const base = String(lang || '').split('-')[0]
  if (!base || base === 'en' || !DATE_LOCALES[base]) return
  try {
    await DATE_LOCALES[base]()
    dayjs.locale(base)
  } catch {
    /* English dates on an Arabic page is a blemish; a blank page is not. */
  }
}
