// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * How a date, a time, a number and an amount of money read.
 *
 * One module, and nothing in the product formats any of the four outside it.
 * That is not tidiness: there were three clocks before this — `dayjsLocal`
 * (right, and guarded), `toLocaleDateString` (the reader's browser rather than
 * the workspace, and in `.js` where the guard did not look), and the server
 * sending `"d MMM, HH:mm"` already rendered, which the browser cannot convert
 * even if it wants to. And five date format strings for two ideas, with two
 * month spellings chosen per call site.
 *
 * The numbers were worse because the damage is invisible: they went through
 * `toLocaleString(undefined, …)`, which follows *the reader's browser
 * language*. A German workspace that sets `#.###,##` saw `1,234.50` or
 * `1.234,50` depending on nothing anybody configured, so two colleagues read
 * the same invoice differently and neither could tell.
 *
 * Every answer here comes from the workspace's own settings, which a person
 * can change on the Regional screen and which wrote through to System
 * Settings and were then read by nothing. They ride the boot payload because a
 * list draws its first numbers before any resource resolves.
 */

import { dayjs, dayjsLocal } from '@/ui'

import { formats as booted } from '@/lib/runtime/boot'

/**
 * Frappe's date spelling, in dayjs's.
 *
 * The System Settings Select offers six — `yyyy-mm-dd`, `dd-mm-yyyy`,
 * `dd/mm/yyyy`, `dd.mm.yyyy`, `mm/dd/yyyy`, `mm-dd-yyyy` — and the three
 * tokens below cover all of them. Translated here rather than stored in
 * dayjs's spelling because the stored string is what the settings screen
 * shows, and a workspace whose setting stopped matching its own dropdown is a
 * setting nobody can reason about.
 */
const DATE_TOKEN = /yyyy|yy|mm|dd/g
const AS_DAYJS = { yyyy: 'YYYY', yy: 'YY', mm: 'MM', dd: 'DD' }

/**
 * The number formats Frappe ships, and what each one's separators are.
 *
 * Derived from frappe/frappe's `number_format.js`, which keeps the same table
 * for the same reason: the string is a *label* for a shape rather than a
 * pattern to be parsed, and `#,###` and `#,###.##` differ in whether the
 * comma is a group separator or a decimal point in a way no general parser
 * gets right without being told.
 */
const SHAPES = {
  '#,###.##': { group: ',', decimal: '.', places: 2 },
  '#.###,##': { group: '.', decimal: ',', places: 2 },
  '# ###.##': { group: ' ', decimal: '.', places: 2 },
  '# ###,##': { group: ' ', decimal: ',', places: 2 },
  "#'###.##": { group: "'", decimal: '.', places: 2 },
  '#, ###.##': { group: ', ', decimal: '.', places: 2 },
  '#,##,###.##': { group: ',', decimal: '.', places: 2, indian: true },
  '#,###.###': { group: ',', decimal: '.', places: 3 },
  '#.###': { group: '.', decimal: '', places: 0 },
  '#,###': { group: ',', decimal: '', places: 0 },
}
const PLAIN = SHAPES['#,###.##']

/** What the workspace said, with a default for every key. */
export function settings() {
  const own = booted || {}
  return {
    date: String(own.date_format || 'yyyy-mm-dd'),
    time: String(own.time_format || 'HH:mm:ss'),
    shape: SHAPES[own.number_format] || PLAIN,
    float: Number(own.float_precision ?? 3),
    money: Number(own.currency_precision ?? PLAIN.places),
    currency: String(own.currency || ''),
  }
}

/** The workspace's day pattern, in dayjs's spelling. */
function datePattern() {
  return settings().date.replace(DATE_TOKEN, (token) => AS_DAYJS[token])
}

/**
 * A day with no time on it: Frappe's Date, as against its Datetime.
 *
 * `2026-09-11` and nothing after it. A Datetime carries a space and a clock,
 * which is what tells the two apart on the way in.
 */
const DATE_ONLY = /^\d{4}-\d{2}-\d{2}$/

/**
 * A value as a dayjs in the reader's own zone, or null.
 *
 * A **datetime string** is a wall clock in the *site's* timezone, so reading
 * it as if it were the reader's own puts an invoice timed 00:30 on the 1st at
 * 20:30 on the 31st for anybody far enough west. `dayjsLocal` is what converts
 * it.
 *
 * A **date string** is not an instant and has no zone to convert *from*. It is
 * somebody's birthday, the day a leave starts, the date an attendance row is
 * about — facts about a calendar rather than about a moment, and the same on
 * both sides of a border. Converting one anyway is how a day marked the 11th
 * came to be drawn as the 10th on every list, calendar and record in the
 * product: midnight site-time is the evening before, west of the site.
 *
 * A **Date or a number** is an absolute instant — a browser's own
 * `Date.now()`, a comment posted in this tab a moment ago — and likewise has
 * nothing to convert from. Running it through `dayjsLocal` would shift it by
 * the site's offset and say a reply posted now arrived four hours ago.
 */
function read(value) {
  if (value === null || value === undefined || value === '') return null
  let when
  if (typeof value !== 'string') when = dayjs(value)
  else if (DATE_ONLY.test(value)) when = dayjs(value)
  else when = dayjsLocal(value)
  return when.isValid() ? when : null
}

/**
 * The month a day is in, named — "September 2026".
 *
 * Not through the workspace's date pattern, because that pattern is about a
 * *day* and has no month name in it. Through dayjs, which is the same clock
 * everything else here reads, rather than `toLocaleDateString`: the browser's
 * answer follows the reader's own language, which nobody configured, so two
 * colleagues looking at the same grid would see two different words.
 */
export function month(value) {
  return read(value)?.format('MMMM YYYY') || ''
}

/**
 * A weekday, as narrowly as a column header can carry — "M", "T", "W".
 *
 * Same reason as above, and one more: a grid of thirty-one columns has about
 * twelve pixels for this, so the initial is not a preference.
 */
export function weekday(value) {
  return read(value)?.format('dd').slice(0, 1) || ''
}

/** A day, in the workspace's format. */
export function date(value) {
  return read(value)?.format(datePattern()) || ''
}

/**
 * A time of day, in the workspace's format.
 *
 * `toTheMinute` drops the seconds from that format rather than replacing it,
 * so a workspace on a 12-hour clock stays on one. What wants it is a fact
 * about somebody's day rather than a log: somebody arrived at 09:41, not at
 * 09:41:07, and the two extra digits are the difference between a line that
 * reads as a fact and one that reads as a timestamp. Anywhere a second really
 * matters — an audit trail, a check-in list — passes nothing and keeps them.
 */
const SECONDS = /[:.]s+/g

export function time(value, { toTheMinute = false } = {}) {
  const pattern = settings().time
  return read(value)?.format(
    toTheMinute ? pattern.replace(SECONDS, '') : pattern) || ''
}

/** A day and a time of day. */
export function moment(value) {
  const when = read(value)
  return when ? when.format(`${datePattern()} ${settings().time}`) : ''
}

/**
 * How long ago, and the one rule that settles where it is right.
 *
 * Under a week it is relative — "3 days ago" is how a person thinks about
 * something that happened this week. Over a week it is a date, because
 * "8 months ago" is less useful than "12 Jan 2026" and every surface was
 * deciding that for itself.
 *
 * The absolute value belongs in a tooltip beside it; `moment()` is what to put
 * there.
 *
 * `bare` drops the "ago" — "3 days" rather than "3 days ago" — which is what a
 * list's meta column wants, where the header already says the word and the
 * space is three characters wide.
 */
export const RELATIVE_DAYS = 7

export function ago(value, bare = false) {
  const when = read(value)
  if (!when) return ''
  if (dayjs().diff(when, 'day') >= RELATIVE_DAYS) return when.format(datePattern())
  return when.fromNow(bare)
}

/**
 * Group the thousands and fix the decimals, the way this workspace writes
 * them. `places` defaults to the workspace's float precision.
 */
export function number(value, places) {
  if (value === null || value === undefined || value === '') return ''
  const amount = Number(value)
  if (!Number.isFinite(amount)) return String(value)

  const { shape, float } = settings()
  const digits = places === undefined ? float : Number(places)
  const fixed = Math.abs(amount).toFixed(Math.max(digits, 0))
  const [whole, part] = fixed.split('.')

  const grouped = shape.indian ? lakhs(whole) : thousands(whole, shape.group)
  const sign = amount < 0 ? '-' : ''
  return part ? `${sign}${grouped}${shape.decimal || '.'}${part}` : `${sign}${grouped}`
}

/** Three at a time, from the right. */
function thousands(digits, group) {
  return digits.replace(/\B(?=(\d{3})+(?!\d))/g, group)
}

/**
 * Two at a time above the first three, which is how the Indian system writes
 * a lakh: 12,34,567 rather than 1,234,567. Frappe ships `#,##,###.##` as a
 * format option, so a workspace can choose it and the general rule is wrong
 * for them.
 */
function lakhs(digits) {
  if (digits.length <= 3) return digits
  const last = digits.slice(-3)
  const rest = digits.slice(0, -3)
  return `${rest.replace(/\B(?=(\d{2})+(?!\d))/g, ',')},${last}`
}

/**
 * An amount of money: the number at the currency's own precision, with its
 * symbol.
 *
 * Its own function because the symbol and the decimal count were deliberately
 * separated — which was right, and left every caller to re-join them, so a
 * currency's own precision was nobody's job. JPY has none and KWD has three;
 * `Intl` knows both, and asking it for the *shape* while formatting the digits
 * ourselves is what keeps the separators the workspace's rather than the
 * browser's.
 */
export function money(value, currency) {
  if (value === null || value === undefined || value === '') return ''
  const code = String(currency || settings().currency || '').toUpperCase()
  const digits = code ? placesFor(code) : settings().money
  const written = number(value, digits)
  const symbol = code ? symbolFor(code) : ''
  return symbol ? `${symbol} ${written}` : written
}

/** How many decimals this currency is written to. */
function placesFor(code) {
  try {
    return new Intl.NumberFormat('en', { style: 'currency', currency: code })
      .resolvedOptions().maximumFractionDigits
  } catch {
    // A code Intl does not know — a workspace's own unit, a crypto ticker.
    // The workspace's money precision is the honest answer.
    return settings().money
  }
}

/** The currency's symbol, or its code where it has none. */
function symbolFor(code) {
  try {
    const parts = new Intl.NumberFormat('en', { style: 'currency', currency: code })
      .formatToParts(0)
    return parts.find((one) => one.type === 'currency')?.value || code
  } catch {
    return code
  }
}

export default { settings, date, time, moment, ago, number, money, RELATIVE_DAYS }
