// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Notifications, and the one door they all go through.
 *
 * Every mutation reports its outcome and every failure is rendered from a
 * normalised Frappe error, so nobody sees a raw traceback or a silent no-op.
 *
 * `toast` is deliberately **not** re-exported. It used to be, and seven files
 * took it — so those outcomes had no sound and their errors were whatever the
 * caller happened to pass rather than a parsed Frappe one.
 * `test_notify_is_the_only_door` is what stops the eighth.
 *
 * Which channel carries which news is a question about **how long the news is
 * true for**, and the table is short:
 *
 *   it worked and you can see it happen   nothing
 *   it worked and you cannot see it       `notifySuccess`, three seconds
 *   it worked and can be taken back       `notifyUndoable`, eight
 *   it failed, about a field              `<ErrorMessage>` under the field
 *   it failed, about the action           `notifyError`, eight
 *   it is broken until you fix it         an `<Alert>` in place
 *
 * The first row is the one that is easy to get wrong in both directions: a
 * toast for something visibly done is noise, and silence for something that
 * happened off screen is a person clicking twice.
 */

import { toast } from 'frappe-ui'

import { normalizeError } from '@/lib/runtime/errors'
import { playSound } from '@/lib/runtime/sound'
import { __ } from '@/lib/runtime/translate'

export function notifySuccess(message, options = {}) {
  playSound('success')
  return toast.success(message, options)
}

export function notifyError(error, options = {}) {
  const { title, message, extra, detail } = normalizeError(error)

  // The traceback goes to the console, never the toast.
  if (detail) console.error(title, detail)

  playSound('error')
  return toast.error(title, {
    description: [message, ...(extra || [])].filter(Boolean).join('\n'),
    duration: 8000,
    ...options,
  })
}

export function notifyInfo(message, options = {}) {
  return toast.info(message, options)
}

/**
 * A warning: it did not fail, and it did not do what you meant either.
 *
 * No sound. A tone for every outcome trains people to stop hearing any of
 * them, and this is the class of news that is usually about the reader's own
 * next move — "select the words first" — rather than about something the
 * product did.
 */
export function notifyWarning(message, options = {}) {
  return toast.warning(message, options)
}

/**
 * It worked, and it can be taken back.
 *
 * The reason this exists is not the toast, it is the fifteen confirmation
 * dialogs. A dialog before a destructive verb is the heavy instrument, and it
 * was reached for everywhere because the light one did not exist: there was
 * no undo anywhere in the product, and the word appeared only in prose
 * explaining that something *could not* be undone.
 *
 * Eight seconds, the same as an error's, because both are news somebody may
 * have to act on. `undo` runs at most once however many times the button is
 * pressed, and a failure inside it is reported the way any other failure is —
 * an undo that silently does nothing is worse than no undo at all.
 */
export function notifyUndoable(message, undo, options = {}) {
  playSound('success')
  let spent = false
  return toast.success(message, {
    duration: 8000,
    action: {
      label: __('Undo'),
      onClick: async () => {
        if (spent) return
        spent = true
        try {
          await undo()
        } catch (raised) {
          notifyError(raised)
        }
      },
    },
    ...options,
  })
}
