// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * How many bytes, said the way a person says it.
 *
 * There were two of these — `onestorage/lib/files.js` for a file row and
 * `UsageBar` for a quota — and they disagreed: one wrote "0 B" for nothing and
 * the other wrote nothing at all, one stopped at GB and the other went to TB,
 * and one rounded through `lib/runtime/format` while the other used
 * `toFixed`. A quota bar reading `1.2 GB` above a file list reading `1,2 GB`
 * is the whole of §A1's argument in one screen.
 *
 * `docs/UNIFICATION.md` §D3.
 */
import { number as count } from '@/lib/runtime/format'

const UNITS = ['B', 'KB', 'MB', 'GB', 'TB']

/**
 * `1.2 MB`, in the reader's own locale — the server sends bytes because it
 * does not know what locale that is.
 *
 * `blank` is what nothing looks like: a file list wants an empty cell and a
 * quota bar wants "0 B", and that is the only thing the two ever disagreed
 * about that was a real difference.
 */
export function sizeText(bytes, { blank = '' } = {}) {
  const size = Number(bytes) || 0
  if (!size) return blank
  const step = Math.min(Math.floor(Math.log(size) / Math.log(1024)), UNITS.length - 1)
  return `${count(size / 1024 ** step, step ? 1 : 0)} ${UNITS[step]}`
}
