// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * SettingsDialog geometry below frappe-ui's own `sm` breakpoint.
 *
 * frappe-ui 1.0.0-beta.55 makes the dialog full-screen on a phone but keeps the
 * desktop shape inside it: the nav stays a vertical column capped at 38vh — 320
 * pixels of tabs before any content on a tall phone — and every panel pads
 * `px-[4.4rem]`, which leaves 249px of a 390px screen and wraps "API host" one
 * word per line.
 *
 * These reflow it into the shape a phone wants: a horizontally scrolling strip
 * of tabs, then the content. They are fallthrough classes on the library's own
 * components rather than a stylesheet override, so nothing here depends on a
 * class name frappe-ui did not publish, and `max-sm:` is the same breakpoint
 * the dialog switches at — one number, not two that can disagree.
 *
 * `tests/test_settings_dialog_geometry.py` pins the upstream values these
 * compensate for; when frappe-ui makes them responsive, that test fails and
 * this module should go.
 */

/**
 * The nav. Row instead of column, scrolling sideways, uncapped height.
 * `[&>div]` is SettingsSidebar's own `space-y-4` wrapper: laid out as a row it
 * needs the gap on the inline axis and no stacking margin on its children.
 */
export const TAB_STRIP = [
  'max-sm:!max-h-none',
  'max-sm:!flex-row',
  'max-sm:!items-center',
  'max-sm:!gap-2',
  'max-sm:!overflow-x-auto',
  'max-sm:!overflow-y-hidden',
  'max-sm:!p-2',
  'max-sm:[&>div]:flex',
  'max-sm:[&>div]:gap-2',
  'max-sm:[&>div>*]:!mt-0',
].join(' ')

/**
 * A group inside the strip: its heading is a row of its own that a strip has no
 * room for, and its items lay out along the strip rather than down it.
 */
export const TAB_GROUP = [
  'max-sm:[&>div:first-child]:hidden',
  'max-sm:[&>div:last-child]:!flex-row',
  'max-sm:[&>div:last-child]:gap-2',
].join(' ')

/** A tab: as wide as its label, never wrapped, never squeezed. */
export const TAB_ITEM = 'max-sm:!w-auto max-sm:shrink-0 max-sm:whitespace-nowrap'

/** A panel's pinned header. */
export const PANEL_HEADER = 'max-sm:!px-4 max-sm:!pt-5'

/**
 * The panel column, so a wide table scrolls instead of stretching the dialog.
 *
 * A flex item's `min-width` defaults to `auto`: it refuses to shrink below its
 * content. SettingsPanel is a flex item of SettingsContent, so a table
 * declaring `min-w-[40rem]` inside an `overflow-x-auto` wrapper does not make
 * the wrapper scroll — it makes the panel grow. Measured on a Pixel 7, the
 * models panel came out 787px wide in a 412px viewport with a third of it
 * unreachable, and `document.scrollWidth` stayed clean the whole time because
 * the dialog clips what overflows. Every catalogue panel had it.
 *
 * Applied to SettingsContent and reaching its panels, so it is one class in one
 * place rather than a prop every panel has to remember.
 */
export const PANEL_CONTENT = '[&>[role=tabpanel]]:min-w-0'

/**
 * A panel's scrolling body. The padding lives on the ScrollArea viewport, which
 * SettingsBody hardcodes, so it is reached through the viewport's data-slot
 * rather than by a class on the component.
 */
export const PANEL_BODY = [
  'max-sm:[&_[data-slot=scroll-area-viewport]]:!px-4',
  'max-sm:[&_[data-slot=scroll-area-viewport]]:!pb-6',
].join(' ')

/**
 * A panel's pinned footer — the row Save lives in.
 *
 * SettingsPanel is a flex column of [header, body, footer] and SettingsBody
 * takes `flex-1`, so a sibling placed after it pins to the bottom with no
 * positioning of its own. It has to be there rather than inside the body: a
 * Save button in the scroll region is off-screen on a phone exactly when the
 * form is long enough to need saving. frappe-ui ships SettingsHeader and
 * SettingsBody but no footer, so this is the family's missing third piece.
 */
export const PANEL_FOOTER = [
  'flex shrink-0 items-center gap-2',
  'border-t border-outline-gray-1 bg-surface-elevation-1',
  'px-4 py-3 sm:px-[4.4rem]',
].join(' ')
