// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * The sanctioned frappe-ui surface.
 *
 * Both SPAs import from here rather than from 'frappe-ui' directly, so what the
 * product may use is one reviewable list instead of whatever each file reached
 * for. ESLint enforces it, and a test asserts this covers everything frappe-ui
 * exports — a component missing here is a component someone will hand-roll.
 *
 * Reach for a component before writing markup. A <div> with divide-y is not a
 * list; a <router-link> with an active class is not a sidebar item. They look
 * close in isolation and wrong beside everything else.
 */

export {
  // ----- Shell -----------------------------------------------------------
  // DesktopShell renders a PageHeaderTarget and a ScrollArea itself, so pages
  // teleport their header up with <PageHeader> rather than laying one out.
  DesktopShell,
  MobileShell,
  MobileNav,
  Rail,
  RailItem,
  ScrollArea,
  ScrollBar,

  // ----- Page header -----------------------------------------------------
  PageHeader,
  PageHeaderBase,
  PageHeaderTitle,
  PageHeaderBackButton,
  PageHeaderMobile,
  PageHeaderMobileTitle,
  PageHeaderTarget,

  // ----- Sidebar ---------------------------------------------------------
  Sidebar,
  SidebarItem,
  SidebarLabel,
  SidebarSection,
  SidebarHeader,
  SidebarCard,
  SidebarCollapseToggle,

  // ----- Settings --------------------------------------------------------
  // A whole family, so settings surfaces are composed rather than hand-built.
  SettingsDialog,
  SettingsSidebar,
  SettingsNavGroup,
  SettingsNavItem,
  SettingsBody,
  SettingsContent,
  SettingsPanel,
  SettingsHeader,
  SettingsRow,

  // ----- Structure -------------------------------------------------------
  Divider,
  Breadcrumbs,
  Tabs,
  TabList,
  TabTrigger,
  TabPanel,
  TabButtons,

  // ----- Actions ---------------------------------------------------------
  Button,
  Dropdown,
  ContextMenu,

  // ----- Form controls ---------------------------------------------------
  FormControl,
  FormLabel,
  TextInput,
  Textarea,
  Password,
  Select,
  Combobox,
  MultiSelect,
  Checkbox,
  Switch,
  Radio,
  RadioGroup,
  Slider,
  Rating,
  DatePicker,
  DateTimePicker,
  DateRangePicker,
  TimePicker,
  Duration,
  FileUploader,
  ErrorMessage,

  // ----- Feedback --------------------------------------------------------
  Alert,
  Badge,
  Progress,
  Spinner,
  LoadingIndicator,
  LoadingText,
  Skeleton,
  Tooltip,
  TooltipProvider,

  // ----- Overlays --------------------------------------------------------
  Dialog,
  Popover,
  HoverCard,
  BottomSheet,
  KeyboardShortcut,
  KeyboardShortcutsDialog,

  // ----- Display ---------------------------------------------------------
  Avatar,
  Icon,
  Tree,
  ItemListRow,
  ThemeSwitcher,

  // ----- Root provider ---------------------------------------------------
  FrappeUIProvider,

  // ----- Imperative ------------------------------------------------------
  toast,
  dialog,

  // ----- Composables -----------------------------------------------------
  usePageMeta,
  useColorScheme,
  useKeyboardShortcut,
  useShellScrolled,
  useFileUpload,

  // ----- Directives ------------------------------------------------------
  vFocus,
  vOnOutsideClick,

  // ----- Data and utilities ----------------------------------------------
  call,
  frappeRequest,
  setConfig,
  getConfig,
  upload,
  dayjs,
  dayjsLocal,
  debounce,
} from 'frappe-ui'

/**
 * The list family. A separate entry point in frappe-ui because it ships its own
 * structural CSS; re-exported here so pages have one import path.
 *
 * `List` takes grid track sizes via `columns` and handles dividers, selection
 * and the active row. Reach for it before writing a table or a stack of divs.
 */
export {
  List,
  ListHeader,
  ListHeaderCell,
  ListHeaderCellSort,
  ListRows,
  ListRow,
  ListCell,
  ListGroup,
} from 'frappe-ui/list'
