// Generated by scripts/gen_frontend.py. Edit that, not this file.

// Sign in through Frappe's own endpoint rather than the login form: the form is
// Frappe's, not ours, and driving it would make every test depend on markup we
// do not own.
//
// `who` names somebody other than the default, which the realtime tests need:
// some things only exist between two people, and Frappe will not tell you that
// *you* are the one looking at a record.
export async function signIn(page, baseURL, who = {}) {
  const response = await page.request.post(`${baseURL}/api/method/login`, {
    form: {
      usr: who.user || process.env.ONEAPP_USER || 'Administrator',
      pwd: who.password || process.env.ONEAPP_PASSWORD || 'Dev-Loop-2026!x',
    },
  })
  if (!response.ok()) {
    throw new Error(`login failed: ${response.status()} ${await response.text()}`)
  }
}

/**
 * Console errors and failed requests, because a page can be broken and silent.
 *
 * Failed requests are collected from the network rather than from the console.
 * The console message for one is "Failed to load resource: the server responded
 * with a status of 404 (NOT FOUND)" — no URL, nothing to tell a broken endpoint
 * from a route that only exists behind nginx. Reading the response gives the
 * URL, which is both a better failure message and the only way to ignore one
 * thing without ignoring everything.
 */
export function collectConsoleErrors(page) {
  const errors = []
  page.on('console', (m) => {
    // Dropped: the network hook below reports the same failure with its URL.
    if (m.type() === 'error' && !/Failed to load resource/.test(m.text())) {
      errors.push(m.text())
    }
  })
  page.on('pageerror', (e) => errors.push(String(e)))
  page.on('response', (r) => {
    if (r.status() >= 400) errors.push(`${r.status()} ${r.url()}`)
  })
  return errors
}

/**
 * Fail on errors that mean something is broken, not on noise.
 *
 * The one worth catching is a fetch whose body is HTML: under our SPA route
 * rules Frappe answers an unknown path with the app's own page at 200, so a
 * mis-built request URL never 404s — it quietly returns a document and the data
 * is simply absent. That is how every useResource call fetched nothing.
 */
const NL = String.fromCharCode(10)

export function expectNoRealErrors(errors) {
  const ignorable = [
    // Logged by frappe-ui during a brief window before a resource resolves;
    // renders correctly and does not throw. Tracked, not silenced everywhere.
    /reading 'charAt'/,
    // A print preview is rendered into a `sandbox=""` iframe on purpose: a
    // print format is HTML somebody in the workspace wrote, and a preview is
    // not a place to run it. Chromium says so once per script the format
    // carries, which is the sandbox working rather than anything failing.
    /Blocked script execution in 'about:/,
    // Realtime is proxied to the socketio port by nginx in production. The
    // development server serves the built SPA with no proxy in front of it, so
    // this 404s locally and only locally — and it did so on every page, which
    // meant this whole check was passing nothing. Realtime is therefore not
    // covered by the browser pass; it is exercised on a real site.
    /\/socket\.io\//,
    // A request the browser cancelled, which is what `fetch` reports when the
    // page navigates out from under one. The Mail screen refetches on a
    // realtime event, so any spec that reloads shortly after acting on a
    // message can lose that refetch mid-flight — and losing it is correct
    // behaviour, not a failure. A server that really fails answers with a
    // status, which the response listener above still catches.
    /TypeError: Failed to fetch/,
  ]
  const real = errors.filter((e) => !ignorable.some((p) => p.test(e)))
  if (real.length) {
    throw new Error('console errors:' + NL + real.join(NL))
  }
}
