"""Capabilities, and the provider task names that map onto them.

Generated by scripts/gen_doctypes.py from scripts/ai_capabilities.py. Do not
edit: the same list fills the AI Model and AI Feature Selects, and a second
hand-maintained copy is how a model ends up in a bucket the settings page does
not offer.
"""

CAPABILITIES = {'Audio Generation': ['text-to-audio', 'music generation', 'audio generation'],
 'Classification': ['text classification', 'image classification', 'classification'],
 'Image Generation': ['text-to-image', 'image-to-image', 'image generation'],
 'Image Understanding': ['image-to-text', 'image to text', 'visual question answering'],
 'Object Detection': ['object detection'],
 'Reranking': ['text reranking', 'reranker', 'rerank'],
 'Speech to Text': ['automatic speech recognition', 'speech recognition', 'transcribe'],
 'Summarization': ['summarization'],
 'Text Embeddings': ['text embeddings', 'embedcontent', 'embedding'],
 'Text Generation': ['text generation', 'generatecontent', 'chat'],
 'Text to Speech': ['text-to-speech', 'text to speech', 'tts'],
 'Translation': ['translation'],
 'Video Generation': ['text-to-video', 'video generation']}

CAPABILITY_NAMES = list(CAPABILITIES)


def for_task(task: str) -> str | None:
	"""The capability a provider's task name means, or None if we do not know.

	None is a real answer. A model whose task we cannot place is left for review
	rather than filed under the nearest-looking capability, because the cost of
	guessing is a feature calling a model that cannot do the job.
	"""
	if not task:
		return None

	needle = task.strip().lower()
	for capability, aliases in CAPABILITIES.items():
		if needle == capability.lower() or needle in aliases:
			return capability
	return None
