// Generated by scripts/gen_frontend.py. Edit that, not this file.

import { computed } from 'vue'
import { useColorScheme } from '@/ui'

/**
 * Light, dark or follow-the-system, in the three shapes the app needs it.
 *
 * Appearance is reachable from the user menu, the phone's More sheet and
 * settings. Three copies of the same list is how one of them ends up missing
 * an option or writing the theme without updating the stored value, so the
 * list and the setter live here and each surface only picks a rendering.
 */
export const SCHEMES = [
  { value: 'light', label: 'Light', icon: 'lucide-sun' },
  { value: 'dark', label: 'Dark', icon: 'lucide-moon' },
  { value: 'system', label: 'System', icon: 'lucide-monitor' },
]

export function useAppearance() {
  const { colorScheme, setColorScheme } = useColorScheme()

  const scheme = computed({
    get: () => colorScheme.value,
    // colorScheme is readonly on purpose: the ref is only a third of the state,
    // alongside the <html> attribute and the stored value. setColorScheme moves
    // all three together.
    set: (value) => setColorScheme(value),
  })

  /** A Dropdown/ContextMenu group — one row per scheme, the current one ticked. */
  const menuGroup = computed(() => ({
    group: 'Appearance',
    options: SCHEMES.map((item) => ({
      label: item.label,
      icon: item.icon,
      selected: colorScheme.value === item.value,
      onClick: () => setColorScheme(item.value),
    })),
  }))

  /** TabButtons options, for a surface with room to show all three at once. */
  const tabOptions = SCHEMES.map((item) => ({
    value: item.value,
    label: item.label,
    iconLeft: item.icon,
  }))

  /** Select options, for a settings row. */
  const selectOptions = SCHEMES.map((item) => ({
    value: item.value,
    label: item.label,
  }))

  return { scheme, menuGroup, tabOptions, selectOptions }
}
