// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Boot data injected by frappe-ui's vite plugin.
 *
 * The plugin's jinjaBootData sub-plugin writes the www page's `boot` context
 * onto `window`, so whatever the page controller puts there is available before
 * the app mounts. Everything here degrades to a sane default, because the dev
 * server serves index.html without Jinja and would otherwise crash on boot.
 */

// The plugin emits `window["<key>"] = <value>` for each key in the page's boot
// context — so `boot.site_name` lands as `window.site_name`, not under a `boot`
// object. Reading window.boot would silently yield undefined and leave the
// socket pointed at the wrong host.
const read = (key, fallback) => (window[key] !== undefined ? window[key] : fallback)

export const siteName = read('site_name', window.location.hostname)
export const socketioPort = read('socketio_port', 9000)
export const csrfToken = read('csrf_token', null)
export const isDev = import.meta.env.DEV

export default { siteName, socketioPort, csrfToken, isDev }
