// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Boot data injected by frappe-ui's vite plugin.
 *
 * The plugin's jinjaBootData sub-plugin writes the www page's `boot` context
 * onto `window`, so whatever the page controller puts there is available before
 * the app mounts. Everything here degrades to a sane default, because the dev
 * server serves index.html without Jinja and would otherwise crash on boot.
 */

const boot = window.boot || window.frappe?.boot || {}

export const siteName = boot.site_name || window.location.hostname
export const socketioPort = boot.socketio_port || 9000
export const csrfToken = boot.csrf_token || window.csrf_token || null
export const isDev = import.meta.env.DEV

export default boot
