// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * What customers call us.
 *
 * The repositories and Frappe apps are oneapp and oneapp_control; those names
 * are internal and stay put. Nothing user-visible should spell either of them,
 * so every surface reads these instead.
 */
export const TENANT_APP = 'OneSpace'
export const ADMIN_APP = 'OneAdmin'
