// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Frappe error normalisation.
 *
 * Frappe reports failures in several shapes: a FrappeResponseError from
 * frappe-ui's fetch layer, a JSON body with `_server_messages` (itself a
 * JSON-encoded array of JSON-encoded objects), an `exception` traceback string,
 * or a bare Error. Rendering any of those raw gives users a stack trace or
 * "[object Object]".
 *
 * This flattens all of them to { title, message, detail }, where `message` is
 * safe to show and `detail` is for the console.
 */

/** Strip the HTML Frappe puts in server messages. */
function stripTags(value) {
  if (typeof value !== 'string') return value
  const el = document.createElement('div')
  el.innerHTML = value
  return (el.textContent || '').trim()
}

/** `_server_messages` is a JSON string containing JSON strings. */
function parseServerMessages(raw) {
  if (!raw) return []
  try {
    const outer = typeof raw === 'string' ? JSON.parse(raw) : raw
    return (Array.isArray(outer) ? outer : [outer])
      .map((entry) => {
        try {
          return typeof entry === 'string' ? JSON.parse(entry) : entry
        } catch {
          return { message: entry }
        }
      })
      .filter(Boolean)
  } catch {
    return []
  }
}

/** Last frame of a traceback is the only useful line for a user-facing hint. */
function lastTracebackLine(exception) {
  if (typeof exception !== 'string') return ''
  const lines = exception.trim().split('\n').filter(Boolean)
  return lines.length ? lines[lines.length - 1].trim() : ''
}

export function normalizeError(error) {
  if (!error) return { title: 'Something went wrong', message: '', detail: null }

  // A string is its own message. Callers hand one over whenever the detail is
  // theirs rather than the server's — a bulk change naming the four records
  // that refused it, say — and without this every one of those rendered as
  // "Something went wrong / No further detail was returned", which is the
  // most confidently useless pair of sentences in the product. It had been
  // doing that on a refused bulk delete since that was written.
  if (typeof error === 'string') {
    return {
      title: 'Something went wrong',
      message: error,
      extra: [],
      indicator: 'red',
      detail: null,
      raw: error,
    }
  }

  const messages = parseServerMessages(
    error.messages || error._server_messages || error.response?._server_messages,
  )

  const first = messages[0] || {}
  const fromServer = stripTags(first.message)

  // FrappeResponseError already carries the parsed fields.
  const title =
    first.title ||
    error.title ||
    (error.name === 'FrappeResponseError' ? 'Request failed' : null) ||
    'Something went wrong'

  const message =
    fromServer ||
    stripTags(error.message) ||
    lastTracebackLine(error.exception) ||
    'No further detail was returned.'

  return {
    title: stripTags(title),
    message,
    // Extra server messages beyond the first, shown as additional lines.
    extra: messages.slice(1).map((m) => stripTags(m.message)).filter(Boolean),
    indicator: first.indicator || error.indicator || 'red',
    detail: error.exception || error.stack || null,
    raw: error,
  }
}

export function errorText(error) {
  const { title, message } = normalizeError(error)
  return message && message !== title ? `${title}: ${message}` : title
}
