// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Every Frappe fieldtype, and what renders it.
 *
 * Generated from scripts/field_types.py, which is checked against Frappe's own
 * `data_fieldtypes` — so a fieldtype Frappe adds fails the build here rather
 * than rendering as a text box that saves a string into a Currency column.
 *
 * `control` is a FormControl type as "FormControl:<type>", or the name of a
 * component in the barrel. `null` means shown but never offered: colour,
 * signature and geolocation have no frappe-ui counterpart, and a control that
 * cannot produce the right shape is worse than none.
 */

export const FIELD_TYPES = {
  "Attach": {
    "cell": "attachment",
    "control": "FileUploader",
    "editable": true,
    "icon": "lucide-paperclip"
  },
  "Attach Image": {
    "cell": "image",
    "control": "FileUploader",
    "editable": true,
    "icon": "lucide-image"
  },
  "Autocomplete": {
    "cell": "text",
    "control": "FormControl:combobox",
    "editable": true,
    "icon": "lucide-text-cursor-input"
  },
  "Barcode": {
    "cell": "text",
    "control": null,
    "editable": false,
    "icon": "lucide-scan-barcode"
  },
  "Check": {
    "cell": "check",
    "control": "Switch",
    "editable": true,
    "icon": "lucide-toggle-left"
  },
  "Code": {
    "cell": "code",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-code"
  },
  "Color": {
    "cell": "color",
    "control": null,
    "editable": false,
    "icon": "lucide-palette"
  },
  "Currency": {
    "cell": "currency",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-wallet"
  },
  "Data": {
    "cell": "text",
    "control": "FormControl:text",
    "editable": true,
    "icon": "lucide-type"
  },
  "Date": {
    "cell": "date",
    "control": "FormControl:date",
    "editable": true,
    "icon": "lucide-calendar"
  },
  "Datetime": {
    "cell": "datetime",
    "control": "FormControl:datetime",
    "editable": true,
    "icon": "lucide-calendar-clock"
  },
  "Duration": {
    "cell": "duration",
    "control": "Duration",
    "editable": true,
    "icon": "lucide-timer"
  },
  "Dynamic Link": {
    "cell": "link",
    "control": "Combobox",
    "editable": true,
    "icon": "lucide-link-2"
  },
  "Float": {
    "cell": "number",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-hash"
  },
  "Geolocation": {
    "cell": "text",
    "control": null,
    "editable": false,
    "icon": "lucide-map-pin"
  },
  "HTML Editor": {
    "cell": "html",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-code-xml"
  },
  "Icon": {
    "cell": "icon",
    "control": null,
    "editable": false,
    "icon": "lucide-shapes"
  },
  "Int": {
    "cell": "number",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-hash"
  },
  "JSON": {
    "cell": "code",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-braces"
  },
  "Link": {
    "cell": "link",
    "control": "Combobox",
    "editable": true,
    "icon": "lucide-link"
  },
  "Long Int": {
    "cell": "number",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-hash"
  },
  "Long Text": {
    "cell": "text",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-align-left"
  },
  "Markdown Editor": {
    "cell": "text",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-file-text"
  },
  "Password": {
    "cell": "hidden",
    "control": "Password",
    "editable": true,
    "icon": "lucide-key-round"
  },
  "Percent": {
    "cell": "percent",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-percent"
  },
  "Phone": {
    "cell": "text",
    "control": "FormControl:tel",
    "editable": true,
    "icon": "lucide-phone"
  },
  "Rating": {
    "cell": "rating",
    "control": "Rating",
    "editable": true,
    "icon": "lucide-star"
  },
  "Read Only": {
    "cell": "text",
    "control": "FormControl:text",
    "editable": false,
    "icon": "lucide-lock"
  },
  "Select": {
    "cell": "badge",
    "control": "FormControl:select",
    "editable": true,
    "icon": "lucide-list"
  },
  "Signature": {
    "cell": "text",
    "control": null,
    "editable": false,
    "icon": "lucide-signature"
  },
  "Slider": {
    "cell": "number",
    "control": "Slider",
    "editable": true,
    "icon": "lucide-sliders"
  },
  "Small Text": {
    "cell": "text",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-align-left"
  },
  "Table": {
    "cell": "hidden",
    "control": null,
    "editable": false,
    "icon": "lucide-table"
  },
  "Table MultiSelect": {
    "cell": "tags",
    "control": "MultiSelect",
    "editable": true,
    "icon": "lucide-tags"
  },
  "Text": {
    "cell": "text",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-align-left"
  },
  "Text Editor": {
    "cell": "html",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-pilcrow"
  },
  "Time": {
    "cell": "time",
    "control": "FormControl:time",
    "editable": true,
    "icon": "lucide-clock"
  }
}

/** Layout fields. They carry no value and are skipped rather than rendered. */
export const LAYOUT_TYPES = [
  "Section Break",
  "Column Break",
  "Tab Break",
  "HTML",
  "Button",
  "Image",
  "Fold",
  "Heading",
  "Attachment Gallery"
]

/** What `options` on a Data field refines the input to. Frappe's own list. */
export const DATA_OPTIONS = {
  "Barcode": "text",
  "Email": "email",
  "IBAN": "text",
  "Name": "text",
  "Phone": "tel",
  "URL": "url"
}

/** DocType State's palette, in Badge themes. */
export const STATE_COLORS = {
  "Blue": "blue",
  "Cyan": "teal",
  "Gray": "gray",
  "Green": "green",
  "Light Blue": "blue",
  "Orange": "orange",
  "Pink": "pink",
  "Purple": "violet",
  "Red": "red",
  "Yellow": "amber"
}

/** Frappe's own word lists, so a status reads the same colour as in the desk. */
const WORD_COLORS = [
  [
    "amber",
    [
      "pending",
      "review",
      "medium",
      "not approved",
      "draft",
      "queued"
    ]
  ],
  [
    "red",
    [
      "open",
      "urgent",
      "high",
      "failed",
      "rejected",
      "error",
      "cancelled",
      "overdue",
      "expired"
    ]
  ],
  [
    "green",
    [
      "closed",
      "finished",
      "converted",
      "completed",
      "complete",
      "confirmed",
      "approved",
      "yes",
      "active",
      "available",
      "paid",
      "success"
    ]
  ],
  [
    "blue",
    [
      "submitted",
      "in progress",
      "working",
      "scheduled"
    ]
  ]
]

// Named rather than counted. Stripping this with a hand-written offset is how
// every FormControl type lost its first letter — "date" became "ate", which is
// not in the union, and FormControl answers an unknown type with a plain text
// box and no warning. So the whole record dialog rendered as text inputs and
// nothing anywhere said so.
const FORM_CONTROL = 'FormControl:'

const FALLBACK = {
  control: FORM_CONTROL + 'text',
  cell: 'text',
  icon: 'lucide-circle-help',
  editable: false,
}

/**
 * How to render one field.
 *
 * An unknown fieldtype falls back to a read-only text cell rather than to an
 * editable one: if we do not know what it is, we do not know how to write it.
 */
export function fieldSpec(field) {
  const base = FIELD_TYPES[field?.fieldtype] || FALLBACK

  // `options` on a Data field says what it really holds — an email, a URL, a
  // phone number — and the browser has better keyboards and validation for
  // each than it does for "text".
  if (field?.fieldtype === 'Data' && DATA_OPTIONS[field.options]) {
    return { ...base, control: FORM_CONTROL + DATA_OPTIONS[field.options] }
  }
  return base
}

/** The FormControl `type`, or null when this field needs a named component. */
export function formControlType(field) {
  const { control } = fieldSpec(field)
  return control && control.startsWith(FORM_CONTROL) ? control.slice(FORM_CONTROL.length) : null
}

/** The component name, or null when a FormControl handles it. */
export function controlComponent(field) {
  const { control } = fieldSpec(field)
  return control && !control.startsWith(FORM_CONTROL) ? control : null
}

export function isLayout(fieldtype) {
  return LAYOUT_TYPES.includes(fieldtype)
}

/**
 * The Badge theme for a value.
 *
 * The doctype's own `states` first — Frappe stores a colour per status right on
 * the doctype, so a badge is coloured by what the doctype declares rather than
 * by anything guessed here. Only then the word lists, which are Frappe's, so a
 * status that has no declared colour still reads the same as it does in the
 * desk. Then gray, which is an answer rather than a failure.
 */
export function valueTheme(value, states = []) {
  if (!value) return 'gray'

  const declared = states.find((s) => s.title === value)
  if (declared) return STATE_COLORS[declared.color] || 'gray'

  const text = String(value).toLowerCase()
  for (const [theme, words] of WORD_COLORS) {
    if (words.some((word) => text.includes(word))) return theme
  }
  return 'gray'
}
