// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Every Frappe fieldtype, and what renders it.
 *
 * Generated from scripts/field_types.py, which is checked against Frappe's own
 * `data_fieldtypes` — so a fieldtype Frappe adds fails the build here rather
 * than rendering as a text box that saves a string into a Currency column.
 *
 * `control` is a FormControl type as "FormControl:<type>", or the name of a
 * component in the barrel. `null` means shown but never offered: colour,
 * signature and geolocation have no frappe-ui counterpart, and a control that
 * cannot produce the right shape is worse than none.
 */

export const FIELD_TYPES = {
  "Attach": {
    "cell": "attachment",
    "control": "FileUploader",
    "editable": true,
    "icon": "lucide-paperclip"
  },
  "Attach Image": {
    "cell": "image",
    "control": "FileUploader",
    "editable": true,
    "icon": "lucide-image"
  },
  "Autocomplete": {
    "cell": "text",
    "control": "FormControl:combobox",
    "editable": true,
    "icon": "lucide-text-cursor-input"
  },
  "Barcode": {
    "cell": "text",
    "control": null,
    "editable": false,
    "icon": "lucide-scan-barcode"
  },
  "Check": {
    "cell": "check",
    "control": "Switch",
    "editable": true,
    "icon": "lucide-toggle-left"
  },
  "Code": {
    "cell": "code",
    "control": "CodeEditor",
    "editable": true,
    "icon": "lucide-code"
  },
  "Color": {
    "cell": "color",
    "control": null,
    "editable": false,
    "icon": "lucide-palette"
  },
  "Currency": {
    "cell": "currency",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-wallet"
  },
  "Data": {
    "cell": "text",
    "control": "FormControl:text",
    "editable": true,
    "icon": "lucide-type"
  },
  "Date": {
    "cell": "date",
    "control": "FormControl:date",
    "editable": true,
    "icon": "lucide-calendar"
  },
  "Datetime": {
    "cell": "datetime",
    "control": "FormControl:datetime",
    "editable": true,
    "icon": "lucide-calendar-clock"
  },
  "Duration": {
    "cell": "duration",
    "control": "Duration",
    "editable": true,
    "icon": "lucide-timer"
  },
  "Dynamic Link": {
    "cell": "link",
    "control": "Combobox",
    "editable": true,
    "icon": "lucide-link-2"
  },
  "Float": {
    "cell": "number",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-hash"
  },
  "Geolocation": {
    "cell": "text",
    "control": null,
    "editable": false,
    "icon": "lucide-map-pin"
  },
  "HTML Editor": {
    "cell": "html",
    "control": "CodeEditor",
    "editable": true,
    "icon": "lucide-code-xml"
  },
  "Icon": {
    "cell": "icon",
    "control": null,
    "editable": false,
    "icon": "lucide-shapes"
  },
  "Int": {
    "cell": "number",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-hash"
  },
  "JSON": {
    "cell": "code",
    "control": "CodeEditor",
    "editable": true,
    "icon": "lucide-braces"
  },
  "Link": {
    "cell": "link",
    "control": "Combobox",
    "editable": true,
    "icon": "lucide-link"
  },
  "Long Int": {
    "cell": "number",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-hash"
  },
  "Long Text": {
    "cell": "text",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-align-left"
  },
  "Markdown Editor": {
    "cell": "text",
    "control": "Editor:markdown",
    "editable": true,
    "icon": "lucide-file-text"
  },
  "Password": {
    "cell": "hidden",
    "control": "Password",
    "editable": true,
    "icon": "lucide-key-round"
  },
  "Percent": {
    "cell": "percent",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-percent"
  },
  "Phone": {
    "cell": "text",
    "control": "FormControl:tel",
    "editable": true,
    "icon": "lucide-phone"
  },
  "Rating": {
    "cell": "rating",
    "control": "Rating",
    "editable": true,
    "icon": "lucide-star"
  },
  "Read Only": {
    "cell": "text",
    "control": "FormControl:text",
    "editable": false,
    "icon": "lucide-lock"
  },
  "Select": {
    "cell": "badge",
    "control": "FormControl:select",
    "editable": true,
    "icon": "lucide-list"
  },
  "Signature": {
    "cell": "text",
    "control": null,
    "editable": false,
    "icon": "lucide-signature"
  },
  "Slider": {
    "cell": "number",
    "control": "Slider",
    "editable": true,
    "icon": "lucide-sliders"
  },
  "Small Text": {
    "cell": "text",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-align-left"
  },
  "Table": {
    "cell": "hidden",
    "control": null,
    "editable": false,
    "icon": "lucide-table"
  },
  "Table MultiSelect": {
    "cell": "tags",
    "control": "MultiSelect",
    "editable": true,
    "icon": "lucide-tags"
  },
  "Text": {
    "cell": "text",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-align-left"
  },
  "Text Editor": {
    "cell": "html",
    "control": "Editor:html",
    "editable": true,
    "icon": "lucide-pilcrow"
  },
  "Time": {
    "cell": "time",
    "control": "FormControl:time",
    "editable": true,
    "icon": "lucide-clock"
  }
}

/** Layout fields. They carry no value and are skipped rather than rendered. */
export const LAYOUT_TYPES = [
  "Section Break",
  "Column Break",
  "Tab Break",
  "HTML",
  "Button",
  "Image",
  "Fold",
  "Heading",
  "Attachment Gallery"
]

/** What `options` on a Data field refines the input to. Frappe's own list. */
export const DATA_OPTIONS = {
  "Barcode": "text",
  "Email": "email",
  "IBAN": "text",
  "Name": "text",
  "Phone": "tel",
  "URL": "url"
}

/** DocType State's palette, in Badge themes. */
export const STATE_COLORS = {
  "Blue": "blue",
  "Cyan": "teal",
  "Gray": "gray",
  "Green": "green",
  "Light Blue": "blue",
  "Orange": "orange",
  "Pink": "pink",
  "Purple": "violet",
  "Red": "red",
  "Yellow": "amber"
}

/** Frappe's own word lists, so a status reads the same colour as in the desk. */
const WORD_COLORS = [
  [
    "amber",
    [
      "pending",
      "review",
      "medium",
      "not approved",
      "draft",
      "queued"
    ]
  ],
  [
    "red",
    [
      "open",
      "urgent",
      "high",
      "failed",
      "rejected",
      "error",
      "cancelled",
      "overdue",
      "expired"
    ]
  ],
  [
    "green",
    [
      "closed",
      "finished",
      "converted",
      "completed",
      "complete",
      "confirmed",
      "approved",
      "yes",
      "active",
      "available",
      "paid",
      "success"
    ]
  ],
  [
    "blue",
    [
      "submitted",
      "in progress",
      "working",
      "scheduled"
    ]
  ]
]

// Named rather than counted. Stripping this with a hand-written offset is how
// every FormControl type lost its first letter — "date" became "ate", which is
// not in the union, and FormControl answers an unknown type with a plain text
// box and no warning. So the whole record dialog rendered as text inputs and
// nothing anywhere said so.
const FORM_CONTROL = 'FormControl:'

const FALLBACK = {
  control: FORM_CONTROL + 'text',
  cell: 'text',
  icon: 'lucide-circle-help',
  editable: false,
}

/**
 * How to render one field.
 *
 * An unknown fieldtype falls back to a read-only text cell rather than to an
 * editable one: if we do not know what it is, we do not know how to write it.
 */
export function fieldSpec(field) {
  const base = FIELD_TYPES[field?.fieldtype] || FALLBACK

  // `options` on a Data field says what it really holds — an email, a URL, a
  // phone number — and the browser has better keyboards and validation for
  // each than it does for "text".
  if (field?.fieldtype === 'Data' && DATA_OPTIONS[field.options]) {
    return { ...base, control: FORM_CONTROL + DATA_OPTIONS[field.options] }
  }
  return base
}

// The prose editor, and the format it round-trips. Frappe's Text Editor and
// Markdown Editor are the same component storing different text, so the table
// names both as `Editor:<format>` rather than as two components that do not
// exist.
const EDITOR = 'Editor:'

/** The FormControl `type`, or null when this field needs a named component. */
export function formControlType(field) {
  const { control } = fieldSpec(field)
  return control && control.startsWith(FORM_CONTROL) ? control.slice(FORM_CONTROL.length) : null
}

/** The component name, or null when a FormControl handles it. */
export function controlComponent(field) {
  const { control } = fieldSpec(field)
  if (!control || control.startsWith(FORM_CONTROL)) return null
  return control.startsWith(EDITOR) ? 'Editor' : control
}

/**
 * The Editor's `format`, or null for every field that is not one.
 *
 * Named rather than sliced at the call site for the reason the FORM_CONTROL
 * comment above gives: a hand-written offset is how every control type once
 * lost its first letter, and an Editor handed a format it does not know
 * renders an empty document rather than complaining.
 */
export function editorFormat(field) {
  const { control } = fieldSpec(field)
  return control && control.startsWith(EDITOR) ? control.slice(EDITOR.length) : null
}

/**
 * Filter operators, ported from Frappe's own filter UI.
 *
 * Frappe writes this as a deny list per fieldtype (`invalid_condition_map`);
 * it is inverted into an allow list here and generated into the server module
 * too, so the menu a person sees and the check the server makes are the same
 * table. `tests/test_field_types.py` reads Frappe's `filter.js` back and fails
 * when the two drift.
 */
export const OPERATORS = {
  "=": "Equals",
  "!=": "Not Equals",
  "like": "Like",
  "not like": "Not Like",
  "in": "In",
  "not in": "Not In",
  "is": "Is",
  ">": "Greater Than",
  "<": "Less Than",
  ">=": "Greater Than Or Equal To",
  "<=": "Less Than Or Equal To",
  "between": "Between",
  "timespan": "Timespan"
}

/** Frappe relabels the comparisons for a date: "Before" reads better than "<". */
export const OPERATOR_LABELS_BY_TYPE = {
  "Date": {
    "<": "Before",
    ">": "After",
    "<=": "On or Before",
    ">=": "On or After"
  },
  "Datetime": {
    "<": "Before",
    ">": "After",
    "<=": "On or Before",
    ">=": "On or After"
  }
}

const VALID_OPERATORS = {
  "Attach": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Attach Image": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Autocomplete": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Barcode": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Check": [
    "="
  ],
  "Code": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Color": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is"
  ],
  "Currency": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Data": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Date": [
    "=",
    "!=",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<=",
    "between",
    "timespan"
  ],
  "Datetime": [
    "is",
    ">",
    "<",
    ">=",
    "<=",
    "between",
    "timespan"
  ],
  "Duration": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Dynamic Link": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Float": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Geolocation": [
    "=",
    "!=",
    "is"
  ],
  "HTML Editor": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Icon": [
    "=",
    "!=",
    "is"
  ],
  "Int": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "JSON": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Link": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is"
  ],
  "Long Int": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Long Text": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Markdown Editor": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Password": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Percent": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Phone": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Rating": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Read Only": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Select": [
    "=",
    "!=",
    "in",
    "not in",
    "is"
  ],
  "Signature": [
    "=",
    "!=",
    "is"
  ],
  "Slider": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Small Text": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Table": [],
  "Table MultiSelect": [],
  "Text": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Text Editor": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Time": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ]
}

/** Frappe's relative-date vocabulary, in its order. */
export const TIMESPANS = [
  {
    "value": "last 7 days",
    "label": "Last 7 Days"
  },
  {
    "value": "last 14 days",
    "label": "Last 14 Days"
  },
  {
    "value": "last 30 days",
    "label": "Last 30 Days"
  },
  {
    "value": "last 90 days",
    "label": "Last 90 Days"
  },
  {
    "value": "last week",
    "label": "Last Week"
  },
  {
    "value": "last month",
    "label": "Last Month"
  },
  {
    "value": "last quarter",
    "label": "Last Quarter"
  },
  {
    "value": "last 6 months",
    "label": "Last 6 Months"
  },
  {
    "value": "last year",
    "label": "Last Year"
  },
  {
    "value": "yesterday",
    "label": "Yesterday"
  },
  {
    "value": "today",
    "label": "Today"
  },
  {
    "value": "tomorrow",
    "label": "Tomorrow"
  },
  {
    "value": "this week",
    "label": "This Week"
  },
  {
    "value": "this month",
    "label": "This Month"
  },
  {
    "value": "this quarter",
    "label": "This Quarter"
  },
  {
    "value": "this year",
    "label": "This Year"
  },
  {
    "value": "next 7 days",
    "label": "Next 7 Days"
  },
  {
    "value": "next 14 days",
    "label": "Next 14 Days"
  },
  {
    "value": "next 30 days",
    "label": "Next 30 Days"
  },
  {
    "value": "next week",
    "label": "Next Week"
  },
  {
    "value": "next month",
    "label": "Next Month"
  },
  {
    "value": "next quarter",
    "label": "Next Quarter"
  },
  {
    "value": "next 6 months",
    "label": "Next 6 Months"
  },
  {
    "value": "next year",
    "label": "Next Year"
  }
]

const DEFAULT_OPERATORS = {
  "Attach": "like",
  "Attach Image": "like",
  "Autocomplete": "like",
  "Barcode": "like",
  "Check": "=",
  "Code": "like",
  "Color": "=",
  "Currency": "=",
  "Data": "like",
  "Date": "between",
  "Datetime": "between",
  "Duration": "=",
  "Dynamic Link": "like",
  "Float": "=",
  "Geolocation": "=",
  "HTML Editor": "like",
  "Icon": "=",
  "Int": "=",
  "JSON": "like",
  "Link": "=",
  "Long Int": "=",
  "Long Text": "like",
  "Markdown Editor": "like",
  "Password": "like",
  "Percent": "=",
  "Phone": "like",
  "Rating": "=",
  "Read Only": "like",
  "Select": "=",
  "Signature": "=",
  "Slider": "=",
  "Small Text": "like",
  "Table": "",
  "Table MultiSelect": "",
  "Text": "like",
  "Text Editor": "like",
  "Time": "="
}

const EQUALITY = ['=', '!=']
const IN = ['in', 'not in']

/** Which operators a filter on this field may use. */
export function operatorsFor(field) {
  return VALID_OPERATORS[field?.fieldtype] || ['=', '!=', 'is']
}

/** What an operator is called on this field. */
export function operatorLabel(field, operator) {
  return OPERATOR_LABELS_BY_TYPE[field?.fieldtype]?.[operator] || OPERATORS[operator] || operator
}

/** What a filter opens on: a substring for text, a range for a date. */
export function defaultOperator(field) {
  // Stored as a JSON array, so an exact match can never hit.
  if (['_assign', '_liked_by'].includes(field?.fieldname)) return 'like'
  return DEFAULT_OPERATORS[field?.fieldtype] || '='
}

/**
 * What the value control has to be, once the operator is known.
 *
 * Frappe does this by rewriting the docfield in `set_fieldtype`. Naming the
 * decision instead means the server can check a value without rendering one,
 * which is why this same function exists on both sides.
 */
export function valueShape(field, operator) {
  if (operator === 'is') return 'set'
  if (operator === 'timespan') return 'timespan'
  if (operator === 'between') return 'range'
  if (IN.includes(operator)) return 'multi'
  const fieldtype = field?.fieldtype
  if (fieldtype === 'Check' || fieldtype === 'Select') return 'choice'
  if (['Link', 'Dynamic Link'].includes(fieldtype) && EQUALITY.includes(operator)) return 'link'
  // Everything else is a plain box, a Link under `like` included: matching part
  // of a name is a text question.
  return 'value'
}

/** Set / Not Set, which is what `is` asks. */
export const IS_OPTIONS = [
  { value: 'set', label: 'Set' },
  { value: 'not set', label: 'Not Set' },
]

/** A checkbox is one of two things, and neither of them is a text box. */
export const CHECK_OPTIONS = [
  { value: '1', label: 'Yes' },
  { value: '0', label: 'No' },
]

export function isLayout(fieldtype) {
  return LAYOUT_TYPES.includes(fieldtype)
}

/**
 * The Badge theme for a value.
 *
 * The doctype's own `states` first — Frappe stores a colour per status right on
 * the doctype, so a badge is coloured by what the doctype declares rather than
 * by anything guessed here. Only then the word lists, which are Frappe's, so a
 * status that has no declared colour still reads the same as it does in the
 * desk. Then gray, which is an answer rather than a failure.
 */
export function valueTheme(value, states = []) {
  if (!value) return 'gray'

  const declared = states.find((s) => s.title === value)
  if (declared) return STATE_COLORS[declared.color] || 'gray'

  const text = String(value).toLowerCase()
  for (const [theme, words] of WORD_COLORS) {
    if (words.some((word) => text.includes(word))) return theme
  }
  return 'gray'
}
