// Generated by scripts/gen_frontend.py. Edit that, not this file.

import { computed } from 'vue'
import { useIsMobile } from './screen'

/**
 * A list's grid tracks, narrowed for a phone.
 *
 * frappe-ui's List takes explicit tracks, and fixed rem tracks add up. Three
 * columns sized for a desktop leave about 60px for the identity column on a
 * 390px screen, so the one thing a row exists to name truncates to "W…" while
 * a plan code and a status pill keep their full width. A phone cannot show
 * every column; it has to show the right ones.
 *
 * Declare each column once, with what it does on a phone:
 *
 *   const list = useListColumns([
 *     { key: 'name', header: 'Workspace', track: 'minmax(0,1fr)' },
 *     { key: 'plan', header: 'Plan', track: '10rem', mobile: false },
 *     { key: 'status', header: 'Status', track: '8rem', mobile: '5.5rem' },
 *   ])
 *
 * `mobile: false` drops the column below the breakpoint; a string narrows its
 * track. `shows(key)` is what the matching cell tests, so the tracks and the
 * cells can never disagree about how many columns there are — which renders as
 * every cell in the row shifted one place left.
 */
export function useListColumns(spec) {
  const isMobile = useIsMobile()

  const visible = computed(() =>
    spec.filter((column) => !isMobile.value || column.mobile !== false),
  )

  const columns = computed(() =>
    visible.value.map((column) =>
      isMobile.value && typeof column.mobile === 'string'
        ? column.mobile
        : column.track,
    ),
  )

  const shows = (key) => visible.value.some((column) => column.key === key)

  // Destructure this. Vue unwraps a ref bound at the top level of `setup`, but
  // not one reached through a property, so holding the result as an object and
  // writing `:columns="list.columns"` hands List a ComputedRef — which fails at
  // `columns.join` with a message that names neither the list nor the ref.
  // `tests/test_frontend_guards.py` fails the build on that shape.
  return { visible, columns, shows }
}
