// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Notifications.
 *
 * Every mutation reports its outcome and every failure is rendered from a
 * normalised Frappe error, so users never see a raw traceback or a silent
 * no-op. Both play a short tone.
 *
 * Pages should not call `toast` directly — these wrappers are what guarantee
 * the sound and the error parsing happen.
 */

import { toast } from 'frappe-ui'

import { normalizeError } from './errors'
import { playSound } from './sound'

export function notifySuccess(message, options = {}) {
  playSound('success')
  return toast.success(message, options)
}

export function notifyError(error, options = {}) {
  const { title, message, extra, detail } = normalizeError(error)

  // The traceback goes to the console, never the toast.
  if (detail) console.error(title, detail)

  playSound('error')
  return toast.error(title, {
    description: [message, ...(extra || [])].filter(Boolean).join('\n'),
    duration: 8000,
    ...options,
  })
}

export function notifyInfo(message, options = {}) {
  return toast.info(message, options)
}

export { toast }
