// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * The single way this app talks to Frappe.
 *
 * Wraps frappe-ui's useCall so that every request in both SPAs gets the same
 * treatment:
 *
 *   - responses unwrapped, so pages read `data` rather than `data.message`
 *   - failures rendered through the Frappe error normaliser and toasted
 *   - mutations announce their result
 *   - lists refresh over the socket instead of polling
 *
 * ESLint forbids importing useCall or call directly, so this cannot be bypassed
 * without a visible disable comment.
 */

import { watch } from 'vue'
import {
  useCall,
  useList,
  useDoc,
  useDoctype,
  call as rawCall,
  frappeRequest,
} from 'frappe-ui'

import { notifyError, notifySuccess } from './notify'
import { onDoctypeChange } from './socket'

/**
 * Unwrap Frappe's envelope.
 *
 * Depending on the endpoint a response arrives as the value, as `{message: …}`,
 * or occasionally as `{message: {message: …}}` when a whitelisted method
 * returns something already enveloped. Pages should never have to care.
 */
export function normalize(data) {
  let value = data
  let depth = 0

  while (
    value &&
    typeof value === 'object' &&
    !Array.isArray(value) &&
    'message' in value &&
    Object.keys(value).length === 1 &&
    depth < 3
  ) {
    value = value.message
    depth += 1
  }

  return value
}

/**
 * A read. Toasts on failure; silent on success.
 *
 * `watch` names doctypes whose changes should trigger a refetch over the
 * socket.
 */
/**
 * Frappe's method endpoints live under /api/method/. useCall concatenates its
 * `url` onto the base without adding that, so a bare dotted method resolves
 * *relative to the current page* — and under our SPA route rules Frappe answers
 * that with the app's own HTML at 200. The fetch then fails parsing JSON rather
 * than 404ing, which is why it went unnoticed: nothing errored, the data was
 * simply never there.
 */
function methodUrl(method) {
  if (method.startsWith('/') || method.startsWith('http')) return method
  return `/api/method/${method}`
}

export function useResource(url, options = {}) {
  const { watch: watchDoctypes = [], silent = false, transform, onError, ...rest } = options

  const resource = useCall({
    url: methodUrl(url),
    transform: (data) => {
      const value = normalize(data)
      return transform ? transform(value) : value
    },
    onError: (error) => {
      if (!silent) notifyError(error)
      onError?.(error)
    },
    ...rest,
  })

  for (const doctype of watchDoctypes) {
    onDoctypeChange(doctype, () => resource.reload())
  }

  return resource
}

/**
 * A write. Always announces its outcome — a save that appears to do nothing is
 * indistinguishable from a broken one.
 */
export function useAction(url, options = {}) {
  const {
    successMessage = 'Saved',
    silent = false,
    transform,
    onSuccess,
    onError,
    ...rest
  } = options

  return useCall({
    url,
    method: 'POST',
    immediate: false,
    transform: (data) => {
      const value = normalize(data)
      return transform ? transform(value) : value
    },
    onSuccess: (data) => {
      if (!silent && successMessage) notifySuccess(successMessage)
      onSuccess?.(data)
    },
    onError: (error) => {
      if (!silent) notifyError(error)
      onError?.(error)
    },
    ...rest,
  })
}

/**
 * Documents and lists, through frappe-ui's own document layer.
 *
 * `useList` / `useDoc` / `useDoctype` are the recommended layer for new code —
 * they share one document store, so a row updated through a list and the same
 * document opened on a detail page stay in step, and they carry pagination and
 * write helpers. Rolling our own on top of `frappe.client.get_list` gave up all
 * of that and shadowed the library's name while doing it.
 *
 * These wrappers exist for the same reason `useResource` does: to apply one
 * error policy, and to refetch over the socket rather than by polling.
 */
export function useDocList(doctype, options = {}) {
  const { watch: watchDoctypes = [doctype], silent = false, onError, ...rest } = options

  const list = useList({
    doctype,
    onError: (error) => {
      if (!silent) notifyError(error)
      onError?.(error)
    },
    ...rest,
  })

  for (const watched of watchDoctypes) {
    onDoctypeChange(watched, () => list.reload())
  }

  return list
}

/**
 * One document. `name` may be a getter, so a detail page can follow its route
 * parameter without a watcher of its own.
 *
 * useDoc reports failures through its `error` ref rather than an `onError`
 * option, so the toast is wired to that.
 */
export function useDocument(doctype, name, options = {}) {
  const { watch: watchDoctypes = [doctype], silent = false, ...rest } = options

  const resource = useDoc({ doctype, name, ...rest })

  if (!silent) {
    watch(
      () => resource.error,
      (error) => error && notifyError(error),
    )
  }

  for (const watched of watchDoctypes) {
    onDoctypeChange(watched, () => resource.reload())
  }

  return resource
}

/**
 * The write side of a doctype — insert, setValue, delete, runDocMethod.
 *
 * Every submit runs independently, so saving two records at once does not
 * cancel either. `frappe.client.set_value` through `callMethod` was one shared
 * request that did.
 */
export function useDocWrites(doctype, options = {}) {
  const { successMessage, silent = false } = options
  const writes = useDoctype(doctype)

  const announce = (fn) => async (...args) => {
    try {
      const result = await fn(...args)
      if (successMessage && !silent) notifySuccess(successMessage)
      return result
    } catch (error) {
      if (!silent) notifyError(error)
      throw error
    }
  }

  return {
    raw: writes,
    insert: announce((values) => writes.insert.submit(values)),
    setValue: announce((values) => writes.setValue.submit(values)),
    delete: announce((name) => writes.delete.submit({ name })),
  }
}

/**
 * One-off call for imperative code. Normalised and toasted like everything else.
 *
 * `method: 'GET'` for reads. frappe-ui's `call()` is POST-only, and a method
 * whitelisted `methods=["GET"]` rejects a POST as a PermissionError — which
 * reads like an auth problem and is not one. That is what made every read on
 * the signup page fail, so the page reported signups closed on a site where
 * they were open. `tests/test_api_calls.py` checks the verb against the
 * whitelist now.
 */
export async function callMethod(method, params = {}, options = {}) {
  const { successMessage, silent = false, method: verb = 'POST' } = options
  try {
    const response =
      verb === 'POST'
        ? await rawCall(method, params)
        : await frappeRequest({ url: method, method: verb, params })
    const data = normalize(response)
    if (successMessage && !silent) notifySuccess(successMessage)
    return data
  } catch (error) {
    if (!silent) notifyError(error)
    throw error
  }
}
