// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * A row has five states and they must all be legible at once.
 *
 * Before this there was one colour doing three jobs. `bg-surface-gray-2` was
 * the hover, the selected file, the open mail thread, the current version and
 * the open record — so in Drive a hovered file and a selected file were the
 * same colour, in Mail a hovered thread and the open one were, and the only
 * surface that told them apart did it with `aria-current`, which is correct,
 * invisible, and read by nobody using a mouse. The engine's own list rows had
 * no hover at all: the *cell* under the pointer greyed and the row did not,
 * which reads as the cell being the thing you are about to act on when
 * clicking it opens the record. And `focus-visible` appeared once in the
 * whole built stylesheet, so tabbing through a list showed nothing.
 *
 * Five states, five treatments, and the two decisions that make them stack:
 *
 *   rest      the surface
 *   hover     a *lighter* step than selection — it is a pointer, not a choice
 *   focus     a 2px inset ring in the accent, no fill
 *   selected  a fill, plus the tick — it is a set, and a set is counted
 *   open      a 2px leading edge in the accent, and `aria-current` kept
 *
 * **Open is an edge and focus is a ring**, which is the whole of it: a row can
 * be open *and* hovered *and* ticked without three fills fighting over one
 * background. Three fills is why there was only ever one.
 *
 * The accent is the workspace's own — `--surface-gray-10` and
 * `--outline-gray-8` are what `lib/shell/theme.js` paints it into — so the
 * edge that says "you are here" is the same colour as the solid button and
 * the tab indicator, in every workspace.
 *
 * `docs/UNIFICATION.md` §B4.
 */

//: What every interactive row carries. `relative` because the open edge is a
//: pseudo-element pinned to the row's own leading edge, `transition-colors`
//: so the hover arrives rather than snapping, and `group/row` so a cell
//: inside it can show its own affordance on the *row's* hover rather than
//: competing with a fill of its own — which is what an editable cell did, and
//: why the cell under the pointer looked like the thing about to be acted on
//: when clicking it opens the record.
export const ROW = 'group/row relative transition-colors'

//: The pointer is over it. A lighter step than selection on purpose: hover
//: answers "which one am I about to touch", and a hovered row inside a
//: selection must still read as part of the selection.
export const HOVER = 'hover:bg-surface-gray-1'

//: The keyboard is on it. A ring rather than a fill, so it survives on top of
//: hover, selection and open — and inset, so it is not clipped by the
//: scroller a list always sits in.
export const FOCUS =
  'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset ' +
  'focus-visible:ring-outline-gray-8'

//: It is in the set being acted on.
export const SELECTED = 'bg-surface-gray-2'

//: It is the one open in the pane beside the list. An edge rather than a
//: fill; `inset-y-1` so it reads as a mark against the row rather than a
//: border between two of them.
export const OPEN =
  "before:absolute before:inset-y-1 before:start-0 before:w-0.5 " +
  'before:rounded-full before:bg-surface-gray-10'

//: Being dragged: the thing under the pointer, faded where it came from.
export const LIFTED = 'opacity-50'

//: Where it would land. The focus ring's shape in the hairline's colour,
//: because it is a place rather than a state of the thing.
export const DROP = 'ring-2 ring-outline-gray-3'

/**
 * The classes for one row, given what is true about it.
 *
 * A function rather than five exported strings at every call site, because
 * the order matters — `SELECTED`'s fill has to come before `HOVER`'s so the
 * hover wins on a selected row — and getting that wrong is invisible until
 * somebody hovers a ticked row.
 */
export function rowState({ selected, open, lifted, drop } = {}) {
  return [
    ROW,
    selected ? SELECTED : '',
    HOVER,
    FOCUS,
    open ? OPEN : '',
    lifted ? LIFTED : '',
    drop ? DROP : '',
  ].filter(Boolean).join(' ')
}

export default { ROW, HOVER, FOCUS, SELECTED, OPEN, LIFTED, DROP, rowState }
