// Generated by scripts/gen_frontend.py. Edit that, not this file.

import { onMounted, onUnmounted, readonly, ref } from 'vue'

/**
 * One breakpoint, shared by both apps.
 *
 * The shell is not responsive CSS — DesktopShell and MobileShell are different
 * components with different slots, so something has to *choose*. Two apps
 * choosing at two widths is how the same account looks like two products on the
 * same tablet.
 *
 * 768px is Tailwind's `md`, so anything that also branches in CSS agrees with
 * this without a second number to keep in step.
 */
const MOBILE_MAX = 767

const mobile = ref(false)
let query = null
let listeners = 0

function apply(event) {
  mobile.value = event.matches
}

export const isMobile = readonly(mobile)

/**
 * Subscribe a component to the breakpoint.
 *
 * Reference-counted around a single MediaQueryList: every shell, header and
 * menu asking the same question shares one listener, and the last one to
 * unmount removes it.
 */
export function useIsMobile() {
  onMounted(() => {
    if (!query) {
      query = window.matchMedia(`(max-width: ${MOBILE_MAX}px)`)
      mobile.value = query.matches
      query.addEventListener('change', apply)
    }
    listeners += 1
  })

  onUnmounted(() => {
    listeners -= 1
    if (listeners <= 0 && query) {
      query.removeEventListener('change', apply)
      query = null
      listeners = 0
    }
  })

  return isMobile
}
