// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Frappe realtime.
 *
 * Frappe's socket.io server namespaces connections by site and pushes a
 * `list_update` event whenever a document changes. Subscribing to the doctypes
 * a page renders keeps it fresh without polling.
 *
 * One socket per app, shared by every subscriber. Subscriptions are reference
 * counted so a component unmounting does not cut off another that still needs
 * the same doctype.
 */

import { io } from 'socket.io-client'
import { onScopeDispose, getCurrentScope } from 'vue'

import { siteName, socketioPort, isDev } from './boot'

let socket = null
const subscribers = new Map()

function socketUrl() {
  // In development Vite serves the SPA, so the socket has to be addressed
  // directly on the bench's socketio port. In production it is proxied on the
  // site's own origin.
  if (isDev) {
    return `${window.location.protocol}//${window.location.hostname}:${socketioPort}/${siteName}`
  }
  return `${window.location.origin}/${siteName}`
}

export function getSocket() {
  if (socket) return socket

  socket = io(socketUrl(), {
    withCredentials: true,
    reconnection: true,
    reconnectionAttempts: Infinity,
    // Back off rather than hammering a bench that is restarting.
    reconnectionDelay: 1000,
    reconnectionDelayMax: 10000,
  })

  socket.on('connect', () => {
    // Re-subscribe after a reconnect; the server forgets on disconnect.
    for (const doctype of subscribers.keys()) {
      socket.emit('doctype_subscribe', doctype)
    }
  })

  socket.on('list_update', (data) => {
    const handlers = subscribers.get(data?.doctype)
    if (handlers) handlers.forEach((fn) => fn(data.name, data))
  })

  return socket
}

/**
 * Call `handler` whenever any document of `doctype` changes.
 * Returns an unsubscribe function, and cleans up automatically inside a
 * component scope.
 */
export function onDoctypeChange(doctype, handler) {
  const sock = getSocket()

  if (!subscribers.has(doctype)) {
    subscribers.set(doctype, new Set())
    sock.emit('doctype_subscribe', doctype)
  }
  subscribers.get(doctype).add(handler)

  const stop = () => {
    const handlers = subscribers.get(doctype)
    if (!handlers) return
    handlers.delete(handler)
    if (handlers.size === 0) {
      subscribers.delete(doctype)
      sock.emit('doctype_unsubscribe', doctype)
    }
  }

  if (getCurrentScope()) onScopeDispose(stop)
  return stop
}

export function closeSocket() {
  if (!socket) return
  socket.close()
  socket = null
  subscribers.clear()
}
