// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Frappe realtime.
 *
 * Frappe's socket.io server namespaces connections by site and pushes a
 * `list_update` event whenever a document changes. Subscribing to the doctypes
 * a page renders keeps it fresh without polling.
 *
 * One socket per app, shared by every subscriber. Subscriptions are reference
 * counted so a component unmounting does not cut off another that still needs
 * the same doctype.
 */

import { io } from 'socket.io-client'
import { onScopeDispose, getCurrentScope } from 'vue'

import { siteName, socketioPort, devServer } from './boot'

let socket = null
const subscribers = new Map()
const documents = new Map()
const viewers = new Map()
const rooms = new Set()

const key = (doctype, name) => `${doctype}/${name}`

function socketUrl() {
  // Whether the socket is same-origin is a question about what is in front of
  // the site, not about how the SPA was built. In production nginx routes
  // `/socket.io/` to the socketio port; on a bench nothing does, so the socket
  // is addressed on the port itself. Frappe's own desk client makes the same
  // call from `window.dev_server`, and this reads the same flag.
  if (devServer) {
    return `${window.location.protocol}//${window.location.hostname}:${socketioPort}/${siteName}`
  }
  return `${window.location.origin}/${siteName}`
}

export function getSocket() {
  if (socket) return socket

  socket = io(socketUrl(), {
    withCredentials: true,
    reconnection: true,
    reconnectionAttempts: Infinity,
    // Back off rather than hammering a bench that is restarting.
    reconnectionDelay: 1000,
    reconnectionDelayMax: 10000,
  })

  socket.on('connect', () => {
    // Re-subscribe after a reconnect; the server forgets on disconnect. Rooms
    // as well as doctypes — a reader whose wifi blinked is still looking at
    // the same record, and the list of who is in it is wrong until they say
    // so again.
    for (const doctype of subscribers.keys()) {
      socket.emit('doctype_subscribe', doctype)
    }
    for (const room of rooms) {
      const [doctype, name] = room.split('/')
      socket.emit('doc_subscribe', doctype, name)
      if (viewers.has(room)) socket.emit('doc_open', doctype, name)
    }
  })

  socket.on('list_update', (data) => {
    const handlers = subscribers.get(data?.doctype)
    if (handlers) handlers.forEach((fn) => fn(data.name, data))
  })

  // One document rather than a doctype. Frappe publishes `doc_update` into the
  // room a `doc_subscribe` joins, and `doc_viewers` into the one `doc_open`
  // joins — the second is how the desk shows who else has the form open.
  socket.on('doc_update', (data) => {
    const handlers = documents.get(key(data?.doctype, data?.name))
    if (handlers) handlers.forEach((fn) => fn(data))
  })

  socket.on('doc_viewers', (data) => {
    const handlers = viewers.get(key(data?.doctype, data?.docname))
    if (handlers) handlers.forEach((fn) => fn(data?.users || []))
  })

  return socket
}

/**
 * Call `handler` whenever any document of `doctype` changes.
 * Returns an unsubscribe function, and cleans up automatically inside a
 * component scope.
 */
export function onDoctypeChange(doctype, handler) {
  const sock = getSocket()

  if (!subscribers.has(doctype)) {
    subscribers.set(doctype, new Set())
    sock.emit('doctype_subscribe', doctype)
  }
  subscribers.get(doctype).add(handler)

  const stop = () => {
    const handlers = subscribers.get(doctype)
    if (!handlers) return
    handlers.delete(handler)
    if (handlers.size === 0) {
      subscribers.delete(doctype)
      sock.emit('doctype_unsubscribe', doctype)
    }
  }

  if (getCurrentScope()) onScopeDispose(stop)
  return stop
}

/**
 * Call `handler` when this one document changes on the server — somebody else
 * saving it, a background job touching it, a workflow moving it on.
 *
 * The server checks the reader may see the document before it lets them into
 * the room, so this is not a way to watch something you cannot open.
 */
export function onDocChange(doctype, name, handler) {
  return joinDoc(doctype, name, documents, handler, 'doc_subscribe', 'doc_unsubscribe')
}

/**
 * Call `handler` with everyone who currently has this document open, including
 * this reader. Frappe calls it the open-doc room, and it is what the desk's
 * row of faces at the top of a form is built on.
 */
export function onDocViewers(doctype, name, handler) {
  return joinDoc(doctype, name, viewers, handler, 'doc_open', 'doc_close')
}

function joinDoc(doctype, name, registry, handler, join, leave) {
  if (!doctype || !name) return () => {}
  const sock = getSocket()
  const room = key(doctype, name)

  // Both rooms need the subscribe: `doc_open` is what publishes the list of
  // viewers, and `doc_subscribe` is what carries the document's own events.
  if (!rooms.has(room)) {
    rooms.add(room)
    sock.emit('doc_subscribe', doctype, name)
  }
  if (!registry.has(room)) {
    registry.set(room, new Set())
    if (join !== 'doc_subscribe') sock.emit(join, doctype, name)
  }
  registry.get(room).add(handler)

  const stop = () => {
    const handlers = registry.get(room)
    if (!handlers) return
    handlers.delete(handler)
    if (handlers.size) return
    registry.delete(room)
    if (leave !== 'doc_unsubscribe') sock.emit(leave, doctype, name)
    // The room itself goes only when nothing is left watching it.
    if (!documents.has(room) && !viewers.has(room)) {
      rooms.delete(room)
      sock.emit('doc_unsubscribe', doctype, name)
    }
  }

  if (getCurrentScope()) onScopeDispose(stop)
  return stop
}

export function closeSocket() {
  if (!socket) return
  socket.close()
  socket = null
  subscribers.clear()
  documents.clear()
  viewers.clear()
  rooms.clear()
}
