// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Notification sounds.
 *
 * Synthesised with WebAudio rather than shipped as audio files: two short tones
 * need no network request, no asset pipeline, and no licensing.
 *
 * Browsers refuse to start an AudioContext before a user gesture, so the
 * context is created lazily on first play and every failure is swallowed — a
 * silent notification is fine, a thrown error inside a toast is not.
 */

const STORAGE_KEY = 'oneapp:sound'

let context = null

function audioContext() {
  if (context) return context
  const Ctor = window.AudioContext || window.webkitAudioContext
  if (!Ctor) return null
  try {
    context = new Ctor()
  } catch {
    context = null
  }
  return context
}

export function soundEnabled() {
  try {
    return localStorage.getItem(STORAGE_KEY) !== 'off'
  } catch {
    // Private mode and blocked storage both throw; default to on.
    return true
  }
}

export function setSoundEnabled(enabled) {
  try {
    localStorage.setItem(STORAGE_KEY, enabled ? 'on' : 'off')
  } catch {
    /* nothing we can do, and nothing worth failing for */
  }
}

/** Two notes: rising for success, falling for failure. */
const TONES = {
  success: [660, 880],
  error: [440, 330],
}

function playTone(frequencies) {
  const ctx = audioContext()
  if (!ctx) return

  // Autoplay policy may leave it suspended until a gesture.
  if (ctx.state === 'suspended') ctx.resume().catch(() => {})

  const now = ctx.currentTime
  frequencies.forEach((frequency, index) => {
    const start = now + index * 0.09
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()

    osc.type = 'sine'
    osc.frequency.value = frequency

    // Short envelope; a click is what you get without the ramps.
    gain.gain.setValueAtTime(0, start)
    gain.gain.linearRampToValueAtTime(0.05, start + 0.01)
    gain.gain.exponentialRampToValueAtTime(0.0001, start + 0.16)

    osc.connect(gain).connect(ctx.destination)
    osc.start(start)
    osc.stop(start + 0.18)
  })
}

export function playSound(kind) {
  if (!soundEnabled()) return
  try {
    playTone(TONES[kind] || TONES.success)
  } catch {
    /* audio is a nicety; never let it break a notification */
  }
}
