// Generated by scripts/gen_frontend.py. Edit that, not this file.

import { computed } from 'vue'

import { useResource } from './resource'

/**
 * The signed-in user.
 *
 * One resource for the whole app: the sidebar, the user menu and anything that
 * greets someone by name all read this rather than each fetching User/me. The
 * desk is not part of the product, so this is the only place anyone sees their
 * own account.
 */
export const currentUser = useResource('frappe.client.get', {
  params: { doctype: 'User', name: 'me' },
  cacheKey: 'oneapp-current-user',
  silent: true,
})

export const user = computed(() => currentUser.data || {})
export const fullName = computed(() => user.value.full_name || user.value.name || '')
export const userImage = computed(() => user.value.user_image || '')
export const email = computed(() => user.value.name || '')
